// ============ 星言旅途 v3：事件扩充数据库（23c）============
// 本片段只追加数据，引擎逻辑在 23b_flip_games.js。
// 约定：
//  - 常规事件沿用 23b 结构 {title,condition?,scene,companionAction,companionLine,interactions,outcomes}
//  - 环境事件 JOURNEY_AMBIENT：无 interactions，顶层直接给 {title,scene,companionAction,companionLine,memory,stars?,souvenir?}
//  - 小游戏 JOURNEY_MINIGAME：带 game 字段（coin/guess/match/find/photo/price/rps/star）
//  - 多人互动 JOURNEY_MULTI：带 members:[{action,line},...]，占位符 {m0}/{m1} 按同行梦角顺序替换
//  - 连锁剧情 JOURNEY_STORIES：{key,name,stages:[...]}，stages 内每段是完整事件结构
//  - 稀有事件 JOURNEY_HIDDEN：低概率金色事件

// ==================== 1. 地点事件扩充（每个地点 +5 左右）====================
(function(){
  var L=JOURNEY_DB.locations;
  L.garden.events=L.garden.events.concat([
    {title:'花店的种子',
      scene:'花店门口摆着一排小纸袋，风一吹，纸袋哗哗响。',
      companionAction:'{name}拿起一袋，翻到背面看了看种植说明。',
      companionLine:'「买一袋回去种吧，等它开花，就当是这次旅行的纪念。」',
      interactions:[{name:'挑一袋',playerAction:'你在纸袋前挑了半天，选了一袋'},{name:'帮{name}选',playerAction:'你帮{name}挑了一袋颜色好看的种子'}],
      outcomes:{
        '挑一袋':{result:'纸袋上印着一种你没见过的花名，名字很好听。',companionReply:'{name}说：「等它开花，我第一个告诉你。」',memory:'在花店买了一袋种子，和{name}约好等它开花。',stars:2,souvenir:'🌱 一袋花种'},
        '帮{name}选':{result:'你挑的那袋，{name}举起来在光里看了看，很喜欢。',companionReply:'{name}小心收进包里：「那就种它了。」',memory:'你帮{name}挑了一袋花种，TA小心地收了起来。',stars:1,souvenir:''}
      }},
    {title:'花园的秋千',
      scene:'花园一角挂着两架秋千，风一吹就轻轻晃。',
      companionAction:'{name}坐上去，用脚尖点了点地。',
      companionLine:'「小时候最喜欢这个了，你也来试试。」',
      interactions:[{name:'坐上去荡',playerAction:'你坐上另一架秋千，和{name}一起荡起来'},{name:'帮TA推',playerAction:'你站到{name}身后，轻轻推TA'}],
      outcomes:{
        '坐上去荡':{result:'两架秋千一前一后荡起来，越荡越高，笑声也跟着飞。',companionReply:'{name}在半空中喊：「再高一点——」',memory:'花园的秋千，和{name}一起荡到最高点。',stars:2,souvenir:''},
        '帮TA推':{result:'你每推一下，{name}就往前荡一截，衣角被风灌得鼓起来。',companionReply:'{name}下来的时候脸有点红：「好久没人帮我推秋千了。」',memory:'你在后面推秋千，{name}说好久没人这样推过TA。',stars:2,souvenir:''}
      }},
    {title:'花园里的蜜蜂',
      scene:'一丛花上停着好几只蜜蜂，腿上都沾着花粉。',
      companionAction:'{name}蹲下来，隔着一段距离看它们工作。',
      companionLine:'「别怕，它们忙着采蜜，没空理我们。」',
      interactions:[{name:'一起蹲着看',playerAction:'你也蹲下来，安静地看蜜蜂飞来飞去'},{name:'找蜂巢',playerAction:'你好奇地问{name}，蜂巢会在哪里'}],
      outcomes:{
        '一起蹲着看':{result:'蜜蜂在一朵花上停了一会儿，又嗡嗡地飞到下一朵，很有秩序。',companionReply:'{name}小声说：「它们好像比我们还会安排行程。」',memory:'和{name}蹲在花丛边，看了一小会儿蜜蜂。',stars:1,souvenir:''},
        '找蜂巢':{result:'你们沿着花丛找了一圈，最后在一棵老树的分叉上看见了蜂巢。',companionReply:'{name}说：「看到了就走吧，别打扰人家。」',memory:'和{name}找到了花园里的蜂巢，又悄悄走开了。',stars:1,souvenir:''}
      }},
    {title:'雨后的花园',
      condition:'雨天',
      scene:'雨刚停，花园里到处都是水珠，叶子被洗得发亮。',
      companionAction:'{name}伸手碰了碰一片叶子，水珠一下子滚落下来。',
      companionLine:'「你看，雨把什么都洗干净了。」',
      interactions:[{name:'甩水珠玩',playerAction:'你轻轻抖了抖枝条，水珠洒了你们一身'},{name:'闻雨后的空气',playerAction:'你深吸一口气，雨后的空气有泥土和草的味道'}],
      outcomes:{
        '甩水珠玩':{result:'水珠簌簌地落下来，{name}躲了一下，还是被溅到了。',companionReply:'{name}笑着抖抖头发：「你故意的吧！」',memory:'雨后的花园，你把水珠甩了{name}一身，TA笑着追你。',stars:2,souvenir:''},
        '闻雨后的空气':{result:'雨后空气清清凉凉的，混着泥土和青草的味道。',companionReply:'{name}也学着吸了吸鼻子：「嗯，是很好闻。」',memory:'雨后的花园，和{name}一起吸了一口带草香的空气。',stars:1,souvenir:''}
      }},
    {title:'花园的小迷宫',
      scene:'花丛被修剪成一条条小通道，弯弯绕绕地通向深处。',
      companionAction:'{name}站在入口，探头往里看了看，又回头看你。',
      companionLine:'「要不要挑战一下？看谁先到中间。」',
      interactions:[{name:'分头挑战',playerAction:'你和{name}分别钻进不同的通道，看谁先到中间'},{name:'一起走',playerAction:'你拉住{name}，说还是一起走吧'}],
      outcomes:{
        '分头挑战':{result:'你在里面绕了两圈，出来时{name}已经站在中间等你了。',companionReply:'{name}得意地晃了晃手里的花：「我赢啦。」',memory:'花园迷宫里，{name}比你先到了中间，还摘了一朵花。',stars:2,souvenir:''},
        '一起走':{result:'你们手拉着手走完迷宫，在中间的小亭子里坐了一会儿。',companionReply:'{name}说：「还是一起走比较好，不会迷路。」',memory:'和{name}手拉手走完了花园的小迷宫。',stars:1,souvenir:''}
      }}
  ]);
  L.cafe.events=L.cafe.events.concat([
    {title:'手冲咖啡',
      scene:'吧台后面，咖啡师把热水绕圈倒进滤杯，香气一下子散开。',
      companionAction:'{name}趴在吧台上，看得出了神。',
      companionLine:'「原来一杯咖啡要这样一圈一圈地冲。」',
      interactions:[{name:'看完整过程',playerAction:'你和{name}一起看完了整杯手冲的过程'},{name:'问咖啡师',playerAction:'你替{name}问咖啡师，这杯是什么豆子'}],
      outcomes:{
        '看完整过程':{result:'咖啡师把冲好的咖啡推过来，杯口飘着淡淡的香气。',companionReply:'{name}端起来闻了闻：「感觉这一杯特别珍贵。」',memory:'和{name}看完了一杯手冲咖啡的全部过程。',stars:2,souvenir:'☕ 手冲咖啡'},
        '问咖啡师':{result:'咖啡师说是埃塞俄比亚的豆子，有果香，{name}听得眼睛发亮。',companionReply:'{name}小声说：「那我要好好尝一尝。」',memory:'在咖啡馆，和{name}聊起了咖啡豆的产地。',stars:1,souvenir:''}
      }},
    {title:'咖啡馆的猫',
      scene:'柜台边蜷着一只胖猫，尾巴一甩一甩，对谁都爱答不理。',
      companionAction:'{name}蹲下来，试探着伸出手。',
      companionLine:'「它好胖……你说它让摸吗？」',
      interactions:[{name:'试着摸',playerAction:'你轻轻摸了摸猫的背，它眯起眼没动'},{name:'看猫的牌子',playerAction:'你发现猫脖子上的牌子上写着它的名字'}],
      outcomes:{
        '试着摸':{result:'猫眯着眼睛蹭了蹭你的手，喉咙里发出咕噜咕噜的声音。',companionReply:'{name}小声说：「它喜欢你呢。」',memory:'咖啡馆的胖猫，被{name}和你摸得咕噜咕噜叫。',stars:1,souvenir:''},
        '看猫的牌子':{result:'牌子上写着「胖福，本店掌柜」。',companionReply:'{name}念完笑出声：「原来是掌柜的。」',memory:'发现咖啡馆的猫是"掌柜的"，叫胖福。',stars:1,souvenir:''}
      }},
    {title:'下午茶时间',
      scene:'下午的阳光斜斜地照进店里，桌上摆着三层点心架。',
      companionAction:'{name}拿起最上面那层的小饼干，端详了一下。',
      companionLine:'「从最上面开始吃，是下午茶的规矩。」',
      interactions:[{name:'按规矩吃',playerAction:'你从顶层开始，一块一块往下吃'},{name:'先吃最想吃的',playerAction:'你直接伸手拿了最下面那层的蛋糕'}],
      outcomes:{
        '按规矩吃':{result:'你们按顺序吃完整架点心，最后一块司康分成了两半。',companionReply:'{name}擦擦手：「果然要有仪式感才好吃。」',memory:'和{name}按规矩吃了一整架下午茶点心。',stars:2,souvenir:''},
        '先吃最想吃的':{result:'你抢先把蛋糕拿了，{name}愣了一下，然后也去拿自己最想吃的。',companionReply:'{name}咬了一口：「你说得对，规矩哪有喜欢重要。」',memory:'下午茶时你和{name}都先拿了最想吃的那块。',stars:1,souvenir:''}
      }},
    {title:'咖啡馆的唱片',
      scene:'墙角放着一台老唱片机，一张黑胶正慢悠悠地转。',
      companionAction:'{name}走过去，看了看唱片封套上的字。',
      companionLine:'「这张专辑，我爷爷家也有。」',
      interactions:[{name:'一起听',playerAction:'你和{name}在唱片机旁边坐下来，听完了一整面'},{name:'看封套',playerAction:'你拿起封套，看上面印着的年份和歌名'}],
      outcomes:{
        '一起听':{result:'音乐有一点沙沙的底噪，反而显得很温柔。',companionReply:'{name}说：「好像回到了小时候的下午。」',memory:'咖啡馆的老唱片，和{name}一起听完了一面。',stars:2,souvenir:''},
        '看封套':{result:'封套上印着三十年前的年份，纸张已经有点发黄。',companionReply:'{name}说：「这比我们岁数都大了。」',memory:'在咖啡馆看了一张比你们岁数还大的唱片。',stars:1,souvenir:''}
      }},
    {title:'角落的单人座',
      scene:'咖啡馆最里面有个朝窗的单人座，桌上放着一本留言册。',
      companionAction:'{name}翻开留言册，从最新的一页往回翻。',
      companionLine:'「你看，来过这里的人都会写一句。」',
      interactions:[{name:'读留言',playerAction:'你和{name}一起读留言册上的字'},{name:'也写一句',playerAction:'你在留言册上写下一句，签上你们的名字'}],
      outcomes:{
        '读留言':{result:'留言册上写着各种小心愿，有一页还画着歪歪的太阳。',companionReply:'{name}指着那页：「这个人应该过得很开心。」',memory:'咖啡馆的留言册，和{name}读到了很多陌生人的话。',stars:1,souvenir:''},
        '也写一句':{result:'你写下一句「今天和一个人来了这里」，{name}在旁边补了个笑脸。',companionReply:'{name}看着那行字：「以后来的人会看到我们。」',memory:'在咖啡馆的留言册上，和{name}一起留了一句话。',stars:2,souvenir:'✏️ 留言册一页'}
      }}
  ]);
  L.bookshop.events=L.bookshop.events.concat([
    {title:'二手书市',
      scene:'书店门口支着摊子，旧书按斤卖，摞得歪歪扭扭。',
      companionAction:'{name}蹲下来翻了一阵，举起一本封面卷边的书。',
      companionLine:'「这本只要两块钱，捡到宝了。」',
      interactions:[{name:'一起淘',playerAction:'你和{name}一起在摊子上翻书'},{name:'帮TA砍价',playerAction:'你帮{name}和老板商量，把书带走了'}],
      outcomes:{
        '一起淘':{result:'你们淘到三本旧书，封面上都盖着别人的藏书章。',companionReply:'{name}抱着书说：「这些书有故事。」',memory:'二手书市上，和{name}淘到了三本带藏书章的旧书。',stars:2,souvenir:'📚 旧书一本'},
        '帮TA砍价':{result:'老板最后摆了摆手：「两块五，拿走拿走。」{name}笑出了声。',companionReply:'{name}说：「你砍价的样子还挺厉害的。」',memory:'你帮{name}在书市上砍了价，TA说你厉害。',stars:1,souvenir:''}
      }},
    {title:'店员推荐的冷门书',
      scene:'店员听完你们的喜好，从柜台下面抽出一本书。',
      companionAction:'{name}接过书，翻开第一页看了起来。',
      companionLine:'「他说这本书他看了五遍，每次感受都不一样。」',
      interactions:[{name:'买下来',playerAction:'你决定买下这本书，带回去慢慢看'},{name:'先借读',playerAction:'你们坐在书店里，把第一章看完了'}],
      outcomes:{
        '买下来':{result:'书的扉页有店员用铅笔写的一行推荐语。',companionReply:'{name}说：「回去我们一起看，看谁先看完。」',memory:'店员推荐的一本冷门书，和{name}约定一起看。',stars:2,souvenir:'📖 冷门好书'},
        '先借读':{result:'第一章读到一半，你们同时抬头，发现对方也看入迷了。',companionReply:'{name}说：「好看吧？我就说。」',memory:'在书店一起看完了那本冷门书的第一章。',stars:2,souvenir:''}
      }},
    {title:'书店的猫',
      scene:'书架顶上一只猫正打着盹，尾巴垂下来，随着呼吸轻轻晃。',
      companionAction:'{name}仰头看了半天，压低声音。',
      companionLine:'「它睡在书上面……这算以书为枕吧。」',
      interactions:[{name:'悄悄拍照',playerAction:'你举起手机，给睡在书上的猫拍了一张'},{name:'猜它叫什么',playerAction:'你和{name}猜这只猫在书店里叫什么名字'}],
      outcomes:{
        '悄悄拍照':{result:'照片里，猫压着一本《时间的秩序》睡得正香。',companionReply:'{name}看着照片说：「它懂得很。」',memory:'书店的猫睡在《时间的秩序》上，被你们拍了下来。',stars:1,souvenir:''},
        '猜它叫什么':{result:'你们猜了一路，从「书页」猜到「墨水」，最后店员说它叫「注脚」。',companionReply:'{name}说：「注脚……这名字起得真好。」',memory:'和{name}猜书店的猫叫什么，最后知道它叫「注脚」。',stars:2,souvenir:''}
      }},
    {title:'找一本绝版书',
      scene:'你在书店的查询机上敲下一本书名，屏幕显示：馆藏 1 本，在顶层书架。',
      companionAction:'{name}把查询机转到你面前。',
      companionLine:'「只有一本了，走，找找看。」',
      interactions:[{name:'一起找',playerAction:'你和{name}一层一层书架找过去'},{name:'问店员',playerAction:'你直接去问店员那本书的位置'}],
      outcomes:{
        '一起找':{result:'你们在顶层书架的角落里找到了它，封面蒙着一层薄灰。',companionReply:'{name}吹了吹灰：「绝版书，找到了。」',memory:'和{name}在书店顶层找到了那本绝版书。',stars:2,souvenir:''},
        '问店员':{result:'店员说那本书刚被借走，你们对视一眼，有点遗憾又有点好笑。',companionReply:'{name}说：「那就给它留个缘分，下次再来。」',memory:'想找的绝版书被借走了，和{name}约好下次再来。',stars:1,souvenir:''}
      }},
    {title:'朗读的角落',
      scene:'书店深处传来轻轻的朗读声，有人在读一本童话。',
      companionAction:'{name}竖起手指「嘘」了一声，悄悄走过去。',
      companionLine:'「我们听听他在读什么。」',
      interactions:[{name:'悄悄听',playerAction:'你和{name}站在书架后，听完了一个小故事'},{name:'也找本书读',playerAction:'你随手拿起一本书，小声给{name}读了一段'}],
      outcomes:{
        '悄悄听':{result:'朗读的人读完合上书，角落安静了几秒，才重新响起翻页声。',companionReply:'{name}小声说：「有人朗读的书店，真好。」',memory:'在书店的角落，和{name}悄悄听完了一个朗读的故事。',stars:2,souvenir:''},
        '也找本书读':{result:'你读了一段，{name}认真听着，听到有趣的地方笑了一下。',companionReply:'{name}说：「你读得挺好的，以后睡前读给我听。」',memory:'你在书店给{name}读了一段书，TA说以后睡前要听。',stars:2,souvenir:''}
      }}
  ]);
  L.beach.events=L.beach.events.concat([
    {title:'寄居蟹',
      scene:'潮水退去的地方，一只小寄居蟹背着小房子在沙上横行。',
      companionAction:'{name}蹲下来，小心翼翼地用指尖碰了碰它的壳。',
      companionLine:'「它好小，背着房子搬家，好辛苦。」',
      interactions:[{name:'看着它走',playerAction:'你和{name}蹲着，看寄居蟹横着爬进一小片海藻里'},{name:'帮它找新壳',playerAction:'你们在附近找了找，有没有更大一点的空壳'}],
      outcomes:{
        '看着它走':{result:'寄居蟹爬进海藻里，只露出一只小小的螯，像在挥手。',companionReply:'{name}说：「晚安，小房主。」',memory:'海边，和{name}蹲着看一只寄居蟹搬进海藻里。',stars:1,souvenir:''},
        '帮它找新壳':{result:'你们找到一枚漂亮的螺旋壳，放在寄居蟹旁边，它犹豫了一下，没换。',companionReply:'{name}笑了：「看来它很喜欢现在这个家。」',memory:'你们给寄居蟹找了一枚新壳，它却没换，像是在念旧。',stars:2,souvenir:'🐚 螺旋空壳'}
      }},
    {title:'沙滩排球',
      scene:'沙滩上架着一张旧球网，有人正打着排球，笑声传得很远。',
      companionAction:'{name}捡起滚到脚边的球，颠了颠。',
      companionLine:'「要不要过去一起玩？我们俩一队。」',
      interactions:[{name:'加入',playerAction:'你拉着{name}跑进场，和陌生人组队打了一局'},{name:'在旁边看',playerAction:'你坐在沙上，看{name}和别人打球'}],
      outcomes:{
        '加入':{result:'你们配合得意外默契，连赢了两球，最后输给了对方也不亏。',companionReply:'{name}擦了擦汗：「跟你一队，感觉挺稳的。」',memory:'沙滩排球，和{name}一队，赢了也输了，都很开心。',stars:2,souvenir:''},
        '在旁边看':{result:'{name}在场上跑得挺利索，你负责在旁边鼓掌叫好。',companionReply:'{name}下场时把球丢给你：「下局你来。」',memory:'你坐在沙滩上看{name}打球，负责鼓掌。',stars:1,souvenir:''}
      }},
    {title:'海边的灯塔',
      scene:'海岸线的尽头立着一座白塔，塔顶的灯在白天也亮着微光。',
      companionAction:'{name}望着灯塔，忽然说想去看看。',
      companionLine:'「你说，守塔的人每天在看什么？」',
      interactions:[{name:'走过去看',playerAction:'你们沿着海岸线，一路走到灯塔下'},{name:'就在远处看',playerAction:'你们站在远处，把灯塔看进风景里'}],
      outcomes:{
        '走过去看':{result:'灯塔下立着一块牌子，写着这座塔守护了多少年。',companionReply:'{name}摸了摸塔身：「它见过很多船吧。」',memory:'和{name}走到灯塔下，摸了摸它晒了一百年的白墙。',stars:2,souvenir:'🗼 灯塔明信片'},
        '就在远处看':{result:'灯塔在蓝天的背景里很白，你们看了很久，像看一幅画。',companionReply:'{name}说：「下次坐船，从海上再看一次。」',memory:'远处看灯塔，{name}说下次要从海上看。',stars:1,souvenir:''}
      }},
    {title:'海风里的纸飞机',
      scene:'风很大，有人折了一只纸飞机，一松手就被卷上了天。',
      companionAction:'{name}也折了一只，举到风里试了试。',
      companionLine:'「你说，它能飞到哪里去？」',
      interactions:[{name:'放飞',playerAction:'你和{name}同时松手，两只纸飞机一起被风卷走'},{name:'写上字再放',playerAction:'你们在纸飞机上写了一行字，才让它飞走'}],
      outcomes:{
        '放飞':{result:'两只纸飞机歪歪扭扭地飞了一阵，先后落进海里。',companionReply:'{name}看着它们：「到海里了，也算远行。」',memory:'在海风里放了两只纸飞机，看它们落进海里。',stars:1,souvenir:''},
        '写上字再放':{result:'纸飞机带着你们写的话飞远了，风一下子把它托得很高。',companionReply:'{name}仰着头：「希望它被人捡到。」',memory:'在海风里放走了一只写着字的纸飞机。',stars:2,souvenir:''}
      }},
    {title:'海上的日出',
      scene:'天还没全亮，海平线泛起一层淡淡的橘色。',
      companionAction:'{name}早早把你叫起来，裹着外套坐在沙滩上。',
      companionLine:'「快看，太阳要出来了。」',
      interactions:[{name:'一起等日出',playerAction:'你和{name}并肩坐着，等太阳跳出海面'},{name:'录下来',playerAction:'你举起手机，录下太阳升起的整个过程'}],
      outcomes:{
        '一起等日出':{result:'太阳先露一个边，然后整个跳出海面，海面一下全亮了。',companionReply:'{name}轻声说：「值了，没白早起。」',memory:'海上的日出，和{name}一起看着太阳跳出海面。',stars:3,souvenir:'🌅 日出照片'},
        '录下来':{result:'手机里录下了从橘色到金红的全过程，最后画面里还有{name}的侧脸。',companionReply:'{name}凑过来看：「嗯，录得不错。」',memory:'录下了一场海上日出，画面里还有{name}的侧脸。',stars:2,souvenir:''}
      }}
  ]);
  L.park.events=L.park.events.concat([
    {title:'野餐',
      scene:'草坪上铺开一张格子布，篮子里装满吃的，风把布角吹起来。',
      companionAction:'{name}盘腿坐下，一样一样往外拿。',
      companionLine:'「我带了这些，你带的可别藏着。」',
      interactions:[{name:'摆开一起吃',playerAction:'你把带的吃的也摆出来，和{name}一起开动'},{name:'先挑TA带的',playerAction:'你伸手去拿{name}带的三明治'}],
      outcomes:{
        '摆开一起吃':{result:'东西摆了一布，你们吃吃聊聊，把一下午都坐过去了。',companionReply:'{name}摸着肚子：「再坐一会儿吧，走不动了。」',memory:'公园的草坪上，和{name}吃了一顿没有时间的野餐。',stars:2,souvenir:''},
        '先挑TA带的':{result:'三明治是{name}自己做的，味道意外地不错。',companionReply:'{name}有点得意：「我做的，厉害吧。」',memory:'野餐时你先尝了{name}做的三明治，味道很不错。',stars:1,souvenir:''}
      }},
    {title:'放风筝',
      scene:'公园上空飘着好几只风筝，风正是合适的时候。',
      companionAction:'{name}买了一只有着长尾巴的风筝，在风里抖了抖线。',
      companionLine:'「你来放，我来拉线，我们试试。」',
      interactions:[{name:'接过线轴',playerAction:'你接过线轴，逆着风跑起来'},{name:'看TA放',playerAction:'你站在旁边，看{name}把风筝放上天'}],
      outcomes:{
        '接过线轴':{result:'风筝晃晃悠悠地升起来，越飞越高，线在手里绷得紧紧的。',companionReply:'{name}在旁边指挥：「松一点，再松一点！」',memory:'公园的风里，你和{name}合力放起了一只长尾巴风筝。',stars:2,souvenir:'🪁 长尾巴风筝'},
        '看TA放':{result:'{name}跑了几步，风筝稳稳地飞上天，在蓝天里摆着尾巴。',companionReply:'{name}把线递给你：「你也拉一会儿。」',memory:'看{name}把风筝放上天，然后把线交到你手里。',stars:1,souvenir:''}
      }},
    {title:'公园的跳蚤市场',
      scene:'公园入口支起一溜小摊，旧玩具、旧书、手工饰品摆得满满当当。',
      companionAction:'{name}在一个卖旧相机的摊子前停下来。',
      companionLine:'「这个相机，拍出来会是什么样呢？」',
      interactions:[{name:'买下旧相机',playerAction:'你买下那台旧相机，说要给{name}拍一张'},{name:'逛别的摊子',playerAction:'你们继续往前逛，发现一个卖手工饰品的摊子'}],
      outcomes:{
        '买下旧相机':{result:'旧相机装上电池还能用，快门声很脆，像回到从前。',companionReply:'{name}在镜头前有点不好意思：「拍好看点。」',memory:'在跳蚤市场买了一台旧相机，给{name}拍了张照片。',stars:2,souvenir:'📷 旧相机'},
        '逛别的摊子':{result:'手工摊上的项链坠子是一片压干的花，{name}拿起看了看。',companionReply:'{name}说：「这个好特别，像把夏天留住了。」',memory:'跳蚤市场上，和{name}看中了一枚压干花的吊坠。',stars:2,souvenir:'🌸 干花吊坠'}
      }},
    {title:'公园的秋千架',
      scene:'树荫下有两架铁秋千，坐板被太阳晒得暖烘烘的。',
      companionAction:'{name}坐上去，慢悠悠地荡着，鞋尖点着地面。',
      companionLine:'「这里的秋千，比花园那架还高一点。」',
      interactions:[{name:'一起荡',playerAction:'你坐上旁边那架，和{name}比谁荡得高'},{name:'站在旁边说话',playerAction:'你站在秋千旁边，和荡着的{name}聊天'}],
      outcomes:{
        '一起荡':{result:'你们比着比着，最后干脆一起荡到最高点，让风把头发吹乱。',companionReply:'{name}下来的时候说：「赢了输了？算平手。」',memory:'公园的秋千，和{name}比了一场平手的荡高比赛。',stars:1,souvenir:''},
        '站在旁边说话':{result:'你站在旁边，{name}荡过来荡过去，话也一句接一句。',companionReply:'{name}说：「你站这儿，我刚好荡到你说的话里。」',memory:'站在秋千旁边和{name}聊天，TA说荡进了你的话里。',stars:2,souvenir:''}
      }},
    {title:'遛狗的人',
      scene:'一只金毛叼着飞盘跑过来，在你脚边绕了一圈，尾巴摇成风扇。',
      companionAction:'{name}蹲下来，金毛立刻把飞盘放到TA手里。',
      companionLine:'「它把飞盘给我了……这是要我跟它玩。」',
      interactions:[{name:'一起扔飞盘',playerAction:'你和{name}轮流扔飞盘，金毛一趟一趟地捡'},{name:'摸摸它',playerAction:'你蹲下来，摸了摸金毛毛茸茸的脑袋'}],
      outcomes:{
        '一起扔飞盘':{result:'金毛捡了十几次都不累，最后趴在你们脚边直喘气。',companionReply:'{name}揉着它的头：「你赢了，休息一下。」',memory:'公园里，和{name}陪一只金毛玩了好久的飞盘。',stars:2,souvenir:''},
        '摸摸它':{result:'金毛舒服地眯起眼睛，把头靠在你手心里。',companionReply:'{name}说：「你看，它都赖上你了。」',memory:'公园里一只金毛把脑袋靠在了你手心。',stars:1,souvenir:''}
      }}
  ]);
  L.rooftop.events=L.rooftop.events.concat([
    {title:'天台晒着的衣物',
      scene:'天台一角晾着几件衬衫和床单，被风吹得鼓起来。',
      companionAction:'{name}伸手扯了扯衣角。',
      companionLine:'「不知道是谁家的，晒在这里，有点可爱的烟火气。」',
      interactions:[{name:'看衣角的花色',playerAction:'你看了看那些衣物的花色，猜是怎么样的人家'},{name:'帮忙整理',playerAction:'你帮被风吹乱的衣物重新夹好夹子'}],
      outcomes:{
        '看衣角的花色':{result:'有一件是蓝底白花的衬衫，还有一双小小的袜子。',companionReply:'{name}说：「感觉是一家三口。」',memory:'天台晒着的衣物，和{name}猜了一户人家。',stars:1,souvenir:''},
        '帮忙整理':{result:'你把吹乱的床单重新夹好，风又吹来，衣角摆了摆。',companionReply:'{name}说：「像帮陌生人完成了一件小事。」',memory:'你帮天台晾着的衣物重新夹好夹子。',stars:1,souvenir:''}
      }},
    {title:'天台的植物',
      scene:'天台角落摆着几盆绿植，还有一盆开着细碎白花的。',
      companionAction:'{name}给其中一盆浇了点水，又小心地摸了摸叶子。',
      companionLine:'「有人在这里种花，说明住顶楼的人很温柔。」',
      interactions:[{name:'一起浇水',playerAction:'你找到一把小水壶，帮{name}一起给花浇水'},{name:'闻花的味道',playerAction:'你凑近那盆白花，闻了闻它的味道'}],
      outcomes:{
        '一起浇水':{result:'水珠落在叶子上，滚了一圈，太阳一照亮晶晶的。',companionReply:'{name}说：「替它的主人谢谢我们。」',memory:'天台上，和{name}一起给陌生人的花浇了水。',stars:1,souvenir:''},
        '闻花的味道':{result:'那盆白花有淡淡的香，不浓，要凑很近才闻得到。',companionReply:'{name}说：「淡的，像偷偷地香。」',memory:'天台的白花有淡淡的香，{name}说它偷偷地香。',stars:1,souvenir:''}
      }},
    {title:'天台看日落',
      scene:'太阳正往楼群后面沉，天空从橘色渐变成淡紫色。',
      companionAction:'{name}把天台上的旧椅子拖到栏杆边。',
      companionLine:'「坐吧，日落就十几分钟，别浪费了。」',
      interactions:[{name:'坐着看完',playerAction:'你和{name}坐着，把日落从头看到尾'},{name:'拍照',playerAction:'你举起手机，把日落和{name}拍在一起'}],
      outcomes:{
        '坐着看完':{result:'太阳沉下去后，天边还剩一缕淡紫，像舍不得走。',companionReply:'{name}说：「明天还会有的。」',memory:'天台上看了一场完整的日落，{name}说明天还会有。',stars:2,souvenir:''},
        '拍照':{result:'照片里天色正从橘转紫，{name}的发梢被光镀了一层边。',companionReply:'{name}看着照片说：「这张以后要留着。」',memory:'天台日落，和{name}留下了一张被光镀边的照片。',stars:2,souvenir:''}
      }},
    {title:'天台的风铃',
      scene:'天台的门框上挂着一串旧风铃，风一过就叮叮当当响。',
      companionAction:'{name}仰头看了一会儿，伸出手轻轻拨了一下。',
      companionLine:'「这个声音，让天台都温柔起来了。」',
      interactions:[{name:'一起拨风铃',playerAction:'你和{name}轮流拨动风铃，听它响出不同的调子'},{name:'听风的方向',playerAction:'你们安静下来，听风从哪个方向把风铃吹响'}],
      outcomes:{
        '一起拨风铃':{result:'风铃被你们拨得叮叮当当，像在合奏一首没有谱的歌。',companionReply:'{name}笑着说：「我们是不是吵到楼下的人了。」',memory:'天台的旧风铃，被你和{name}拨了一下午。',stars:1,souvenir:''},
        '听风的方向':{result:'风一阵一阵的，风铃响一阵停一阵，像在和谁说话。',companionReply:'{name}说：「它在说，今天有风，明天天晴。」',memory:'在天台听风铃说话，{name}说它在报明天的天气。',stars:1,souvenir:''}
      }},
    {title:'天台的旧椅子',
      scene:'天台角落有一把旧藤椅，坐下去会发出吱呀一声。',
      companionAction:'{name}小心翼翼地坐下去，藤椅吱呀响了一下。',
      companionLine:'「这把椅子，应该坐过很多个黄昏了。」',
      interactions:[{name:'挤着坐',playerAction:'你挤到藤椅边上，两人一起晃着'},{name:'让TA独享',playerAction:'你靠在栏杆上，让{name}独享这把椅子'}],
      outcomes:{
        '挤着坐':{result:'藤椅吱呀吱呀地晃，你们挤在一起，谁也没嫌挤。',companionReply:'{name}说：「再晃就要散架了，但挺舒服的。」',memory:'和{name}挤在天台一把吱呀作响的旧藤椅上。',stars:2,souvenir:''},
        '让TA独享':{result:'{name}窝在藤椅里，你靠在栏杆上，各占一个角度看天。',companionReply:'{name}说：「椅子让给我，那你站着可别累着。」',memory:'天台上，你把旧藤椅让给了{name}，自己靠栏杆看天。',stars:1,souvenir:''}
      }}
  ]);
})();

// ==================== 2. 互动事件扩充（双人互动 +20）====================
JOURNEY_DB.interact=JOURNEY_DB.interact.concat([
  {title:'一起拍照',
    scene:'路边有一面好看的墙，阳光正好落在上面。',
    companionAction:'{name}背靠着墙，摆了个姿势，又觉得别扭，站直了。',
    companionLine:'「帮我拍一张？拍得不好我可要重来。」',
    interactions:[{name:'认真拍',playerAction:'你举起手机，认真给{name}拍了一张'},{name:'一起合照',playerAction:'你举起手机，说一起拍一张合照'}],
    outcomes:{
      '认真拍':{result:'照片里{name}笑得有点拘谨，但很好看。',companionReply:'{name}看着照片：「还行，这张留下。」',memory:'路边那面墙下，你给{name}拍了一张好看的照片。',stars:1,souvenir:''},
      '一起合照':{result:'你们挤进同一个镜头，阳光刚好，谁也没躲开。',companionReply:'{name}看着合照说：「这张得收进手账。」',memory:'和{name}在好看的墙前面拍了一张合照。',stars:2,souvenir:'📸 墙前的合照'}
    }},
  {title:'猜对方喜欢什么',
    scene:'路边有家小饰品店，橱窗里摆着各种小东西。',
    companionAction:'{name}趴在橱窗前，忽然问你。',
    companionLine:'「你猜，这里面哪一件是我最喜欢的？」',
    interactions:[{name:'猜TA的',playerAction:'你观察了一会儿，指了一样东西'},{name:'说自己的',playerAction:'你指着橱窗里自己最喜欢的那件，问{name}猜不猜得到'}],
    outcomes:{
      '猜TA的':{result:'你指的是一枚海星形状的胸针，{name}愣了一下，点了点头。',companionReply:'「猜对了。你怎么知道的？」',memory:'你猜中了{name}最喜欢的东西，是一枚海星胸针。',stars:2,souvenir:''},
      '说自己的':{result:'你指着那件东西，{name}歪头看了看，说你眼光不错。',companionReply:'「那我们扯平了，你喜欢的我也记下了。」',memory:'在饰品店橱窗前，你们互相猜中了对方喜欢的东西。',stars:2,souvenir:''}
    }},
  {title:'互相挑礼物',
    scene:'纪念品店的货架上摆着各种小物件，看得人眼花。',
    companionAction:'{name}拿起一个又放下，拿起另一个又看看你。',
    companionLine:'「你说，送人礼物是送实用的好，还是送好玩的？」',
    interactions:[{name:'挑给TA',playerAction:'你在货架上挑了一样，说是给你的{name}的'},{name:'让TA挑',playerAction:'你说让{name}自己挑，你会喜欢TA挑的'}],
    outcomes:{
      '挑给TA':{result:'你挑了一个小小的木头小马，{name}拿在手里，翻来覆去地看。',companionReply:'「那我收下了，不许反悔。」',memory:'你给{name}挑了一个木头小马，TA收得很小心。',stars:2,souvenir:'🎁 木头小马'},
      '让TA挑':{result:'{name}挑了一枚带铃铛的钥匙扣，别在了你的包上。',companionReply:'「戴好，这是凭证，以后可以找我兑换任何东西。」',memory:'{name}给你挑了一枚带铃铛的钥匙扣，说是凭证。',stars:2,souvenir:'🔔 铃铛钥匙扣'}
    }},
  {title:'比谁先找到',
    scene:'你们路过一片小广场，喷泉边有很多人在散步。',
    companionAction:'{name}忽然指着前方。',
    companionLine:'「那边有个卖冰淇淋的，比谁先到，输的请客。」',
    interactions:[{name:'跑起来',playerAction:'你撒腿就跑，回头对{name}喊'},{name:'慢悠悠走',playerAction:'你不紧不慢地走，等{name}先跑'}],
    outcomes:{
      '跑起来':{result:'你跑得比风快，先到了摊子前，回头冲{name}挥手。',companionReply:'{name}气喘吁吁地赶到：「行，你赢了，我请。」',memory:'喷泉边的赛跑，你赢了，{name}请你吃了冰淇淋。',stars:1,souvenir:'🍦 赢来的冰淇淋'},
      '慢悠悠走':{result:'{name}跑过去又跑回来，买了两支，递给你一支。',companionReply:'「你不跑，那就两支都算我的。」',memory:'比谁先到冰淇淋摊，你没跑，{name}还是买了两支。',stars:1,souvenir:''}
    }},
  {title:'一起看风景',
    scene:'河边有一段木栈道，水面倒着整片天空。',
    companionAction:'{name}在栈道边坐下来，脚悬在水面上方。',
    companionLine:'「这里的风景，像画错色的天空。」',
    interactions:[{name:'挨着坐',playerAction:'你在{name}旁边坐下，把脚也悬出去'},{name:'看水里的倒影',playerAction:'你指着水面，说看我们的倒影'}],
    outcomes:{
      '挨着坐':{result:'水面轻轻晃着，把你们的倒影揉碎又拼好。',companionReply:'{name}说：「坐在这里，时间好像也变慢了。」',memory:'河边的木栈道，和{name}坐着看水把天空揉碎。',stars:2,souvenir:''},
      '看水里的倒影':{result:'水里的倒影和你们一起动，像另一个世界的你们。',companionReply:'{name}说：「那要是捞起来，会捞到另一个我们吗？」',memory:'在河边看倒影，{name}说想捞起另一个你们。',stars:1,souvenir:''}
    }},
  {title:'分享食物',
    scene:'路边小吃摊刚出炉的东西冒着热气，香味勾人。',
    companionAction:'{name}买了一份，先递到你嘴边。',
    companionLine:'「尝尝，这个趁热最好吃。」',
    interactions:[{name:'咬一口',playerAction:'你咬了一口，烫得直吹气'},{name:'也买一份',playerAction:'你说那我也买一份，咱们换着吃'}],
    outcomes:{
      '咬一口':{result:'烫是烫，但味道确实好，你直点头。',companionReply:'{name}笑了：「好吃吧，我就知道。」',memory:'路边的小吃，{name}先递到你嘴边的那一口特别香。',stars:1,souvenir:''},
      '也买一份':{result:'你们一人一份，换着尝了两家的味道。',companionReply:'{name}说：「换着吃，等于吃了四份。」',memory:'路边摊，和{name}换着吃了两份小吃。',stars:1,souvenir:''}
    }},
  {title:'一起避雨',
    scene:'雨点忽然落下来，你们躲进路边的电话亭里。',
    companionAction:'{name}把外套往你那边拢了拢，电话亭一下子变得很小。',
    companionLine:'「这个雨，感觉一时半会儿停不了。」',
    interactions:[{name:'等雨停',playerAction:'你们挤在电话亭里，等雨慢慢变小'},{name:'讲个笑话',playerAction:'你讲了个笑话，{name}在电话亭里笑出声'}],
    outcomes:{
      '等雨停':{result:'雨声打在玻璃上，电话亭里安静又暖和。',companionReply:'{name}说：「像被雨困在一个小盒子里。」',memory:'和{name}躲进路边电话亭，等一场雨下完。',stars:2,souvenir:''},
      '讲个笑话':{result:'你的笑话讲到一半，雨声小了，你们一起笑出声。',companionReply:'{name}擦擦眼角：「这个笑话值一场雨。」',memory:'电话亭里躲雨，你一个笑话把{name}逗笑了。',stars:1,souvenir:''}
    }},
  {title:'帮对方整理东西',
    scene:'风吹过来，{name}的围巾被吹散了一角。',
    companionAction:'{name}手忙脚乱地拢着围巾，发梢也乱了。',
    companionLine:'「这个风，来得真不是时候。」',
    interactions:[{name:'帮TA整理',playerAction:'你伸手帮{name}把围巾重新系好'},{name:'帮TA挡风',playerAction:'你站到{name}迎风的那一边'}],
    outcomes:{
      '帮TA整理':{result:'你系围巾的时候，{name}忽然安静下来，低着头没动。',companionReply:'过了几秒，{name}轻声说：「谢谢。」',memory:'风里，你帮{name}重新系好了围巾。',stars:2,souvenir:''},
      '帮TA挡风':{result:'你站过去，风被挡住了大半，{name}的头发终于不乱飞了。',companionReply:'{name}抬眼看了看你：「还挺会挡风的。」',memory:'你帮{name}挡住了一整面的风。',stars:1,souvenir:''}
    }},
  {title:'互相画画像',
    scene:'公园的长椅上，你们各自捡了一根树枝，在沙地上画。',
    companionAction:'{name}画了几笔，偷偷抬头看了你一眼，又低头补了几笔。',
    companionLine:'「我画完了，你先别看，画好了叫你看。」',
    interactions:[{name:'先看TA的',playerAction:'你凑过去看{name}画了什么'},{name:'画自己的',playerAction:'你低着头，认真地画{name}的画像'}],
    outcomes:{
      '先看TA的':{result:'沙地上画着一个圆脑袋、几根头发的人，还挺像你的。',companionReply:'{name}有点不好意思：「像不像？」',memory:'{name}在沙地上画了你，圆脑袋，几根头发。',stars:1,souvenir:''},
      '画自己的':{result:'你画完抬头，{name}已经画完了，两只画像并排躺在沙上。',companionReply:'{name}看着两个画像：「配成一对。」',memory:'沙地上的画像，你和{name}画了彼此，配成一对。',stars:2,souvenir:''}
    }},
  {title:'交换纪念品',
    scene:'旅途过半，你们在路边的小摊上各自挑了一样小东西。',
    companionAction:'{name}把挑好的东西递到你面前，手心摊开。',
    companionLine:'「这个给你。不是买的礼物，是我挑的。」',
    interactions:[{name:'交换',playerAction:'你也把挑好的东西放进{name}手心'},{name:'先看看',playerAction:'你小心地看了看{name}递来的东西'}],
    outcomes:{
      '交换':{result:'你的是贝壳风铃，{name}的是石头刻的星。你们换了个手。',companionReply:'{name}说：「这样，就等于两个人都有了两样。」',memory:'旅途上，你们交换了各自挑的纪念品。',stars:2,souvenir:'🐚 交换的纪念品'},
      '先看看':{result:'{name}递来的是一个木刻的小人，眉眼有点歪。',companionReply:'「摊主说，这是他自己刻的，全世界只有一个。」',memory:'{name}送了你一个全世界只有一个的木刻小人。',stars:2,souvenir:'🪵 木刻小人'}
    }},
  {title:'互相学一句话',
    scene:'你们路过一个说方言的老巷子，老人们的对话像唱歌。',
    companionAction:'{name}学了两句，发音怪怪的，自己先笑了。',
    companionLine:'「你听我这个，像不像？」',
    interactions:[{name:'教TA',playerAction:'你教{name}学了一句当地话'},{name:'学TA',playerAction:'你学着{name}刚才的口音说了一遍，也怪怪的'}],
    outcomes:{
      '教TA':{result:'{name}学得很认真，舌头都打结了，最后终于说对了一句。',companionReply:'「对了对了！这句我记住了。」',memory:'老巷子里，你教会了{name}一句当地话。',stars:1,souvenir:''},
      '学TA':{result:'你也说得怪腔怪调，两个人对着笑了半天。',companionReply:'「行了，我们两个谁也别说谁。」',memory:'老巷子里，你们互相学着说对方都不会的话。',stars:1,souvenir:''}
    }},
  {title:'写旅行日记',
    scene:'傍晚，你们坐在旅馆门口，摊开一本新的笔记本。',
    companionAction:'{name}翻开第一页，写了一行字，又划掉了。',
    companionLine:'「写旅行日记好难，第一天就不知道怎么写。」',
    interactions:[{name:'帮TA起头',playerAction:'你替{name}想了个开头，写了下来'},{name:'一起写',playerAction:'你说一人写一句，轮流写下去'}],
    outcomes:{
      '帮TA起头':{result:'你写下「今天去了很多地方，但记住的都是小事」，{name}接着写下去。',companionReply:'「这个开头好，后面的我来。」',memory:'旅馆门口，你帮{name}开了旅行日记的头。',stars:1,souvenir:''},
      '一起写':{result:'你们一人一句，日记越写越长，从旅途写到了晚饭。',companionReply:'{name}合上本子：「这本日记，以后要收好。」',memory:'和{name}一人一句，写了一篇旅行日记。',stars:2,souvenir:'📓 旅行日记'}
    }},
  {title:'数脚步',
    scene:'回去的路上，路灯一盏一盏地亮起来。',
    companionAction:'{name}忽然放慢脚步，认真数起自己的步子。',
    companionLine:'「数到一百步之前，看能不能走到那个路口。」',
    interactions:[{name:'一起数',playerAction:'你和{name}一起数着步子走'},{name:'数TA的',playerAction:'你数着{name}的步子，看和TA自己数的一不一样'}],
    outcomes:{
      '一起数':{result:'数到一百的时候，正好踩在路口的路灯下。',companionReply:'{name}说：「准吧？说走到就走到。」',memory:'路灯下，和{name}一起数了一百步，正好到路口。',stars:1,souvenir:''},
      '数TA的':{result:'你数的和{name}自己数的差了三步，两个人数着数着就吵起来了。',companionReply:'「肯定是你少数了，我脚长。」',memory:'路灯下，和{name}因为三步之差争论了一路。',stars:1,souvenir:''}
    }},
  {title:'认路标',
    scene:'路口的指示牌上写着附近的地名，有的名字很好笑。',
    companionAction:'{name}指着路牌念出来，念完自己先笑了。',
    companionLine:'「这个地名，念出来好像在唱歌。」',
    interactions:[{name:'编故事',playerAction:'你给这个地名编了个来历'},{name:'拍照',playerAction:'你举起手机，把这块路牌拍了下来'}],
    outcomes:{
      '编故事':{result:'你编的来历越说越离谱，{name}笑得蹲在了地上。',companionReply:'「不行了，我要把这个故事记下来。」',memory:'路口的路牌，你给它编了个离谱的来历，{name}笑到蹲下。',stars:1,souvenir:''},
      '拍照':{result:'照片里的路牌被夕阳镀成金色，像一块会发光的牌子。',companionReply:'{name}看着照片：「以后看到这张，就会想起今天。」',memory:'夕阳下拍了一块路牌，{name}说会想起今天。',stars:1,souvenir:''}
    }},
  {title:'分享童年零食',
    scene:'小卖部的货架上有种包装很旧的零食，像从童年穿越来的。',
    companionAction:'{name}盯着那包零食看了好一会儿。',
    companionLine:'「这个我小时候吃过，现在居然还有卖。」',
    interactions:[{name:'买一包',playerAction:'你买了两包，一人一包，拆开来吃'},{name:'问TA的味道',playerAction:'你问{name}，小时候吃这个是什么味道'}],
    outcomes:{
      '买一包':{result:'味道和记忆里的不太一样，但{name}还是吃得很认真。',companionReply:'「没变，就是这个味儿。」',memory:'小卖部，和{name}一起吃了包童年时代的零食。',stars:1,souvenir:''},
      '问TA的味道':{result:'{name}讲起小时候放学买零食的事，讲着讲着停不下来。',companionReply:'「那时候一包两毛钱，能开心一整个下午。」',memory:'听{name}讲了一下午童年零食的故事。',stars:2,souvenir:''}
    }},
  {title:'互相起外号',
    scene:'你们路过一片睡莲池，池边立着块牌子：请勿投喂。',
    companionAction:'{name}看着你的侧脸，忽然笑了。',
    companionLine:'「我决定了，从今天起叫你『慢半拍』，因为你走路总比我慢一点。」',
    interactions:[{name:'回敬一个',playerAction:'你也给{name}起了个外号'},{name:'不认账',playerAction:'你说这不公平，要给TA换个更好听的'}],
    outcomes:{
      '回敬一个':{result:'你叫TA「带路狂」，因为TA总走在前面。外号就这么定下了。',companionReply:'「行，那我们扯平了，慢半拍和带路狂。」',memory:'睡莲池边，你们互相起了外号，还都很满意。',stars:1,souvenir:''},
      '不认账':{result:'你冥思苦想，最后叫TA「晴天包」，因为TA出现的时候天气都很好。',companionReply:'「这个……还行，我收下了。」',memory:'你给{name}起名叫「晴天包」，TA收下了。',stars:2,souvenir:''}
    }},
  {title:'帮对方实现小愿望',
    scene:'路边有棵挂满红色布条的许愿树，风把布条吹得簌簌响。',
    companionAction:'{name}踮起脚，把一条空白的红布条挂在最低的树枝上。',
    companionLine:'「我没写愿望。你说，许愿树会不会记得没写字的愿望？」',
    interactions:[{name:'写一个',playerAction:'你取了一条布条，写下一行字挂上去'},{name:'替TA许',playerAction:'你说，那我替你把这个愿望记住了'}],
    outcomes:{
      '写一个':{result:'你在布条上写「希望能一直这样走下去」，和{name}的空布条挂在一起。',companionReply:'{name}看着两条布条：「那我的愿望，就是这条。」',memory:'许愿树下，你写下的愿望和{name}的空白布条挂在了一起。',stars:2,souvenir:''},
      '替TA许':{result:'你说记住了{name}的愿望，{name}看着你，点了点头。',companionReply:'「那你可得记牢了，别忘。」',memory:'许愿树下，你说会记住{name}没写出来的愿望。',stars:2,souvenir:''}
    }},
  {title:'一起发呆',
    scene:'下午的广场上，鸽子在地上踱步，阳光很好。',
    companionAction:'{name}在长椅上坐下来，什么都不干，就发呆。',
    companionLine:'「我们什么都不想，就坐十分钟，怎么样？」',
    interactions:[{name:'跟着发呆',playerAction:'你在{name}旁边坐下，一起放空'},{name:'偷偷看TA',playerAction:'你假装发呆，偷偷看了{name}一眼'}],
    outcomes:{
      '跟着发呆':{result:'十分钟里，你们谁也没说话，鸽子踱过来又踱走。',companionReply:'{name}说：「好了，发呆时间结束，满血复活。」',memory:'广场的长椅上，和{name}一起发了十分钟的呆。',stars:1,souvenir:''},
      '偷偷看TA':{result:'你偷看的那一眼正好被{name}逮到，TA眯起眼笑了。',companionReply:'「你发呆的时候，眼睛好像没闭上。」',memory:'假装发呆偷看{name}，被TA逮了个正着。',stars:1,souvenir:''}
    }},
  {title:'学对方走路',
    scene:'回去的巷子里，路灯把影子拉得长长的。',
    companionAction:'{name}忽然学起你走路的姿势，步子故意迈得大大的。',
    companionLine:'「你就是这么走的！像只企鹅。」',
    interactions:[{name:'学回去',playerAction:'你也学{name}走路，两个人像在演默剧'},{name:'追着TA跑',playerAction:'你作势要追{name}，TA笑着往前跑'}],
    outcomes:{
      '学回去':{result:'你们在路灯下互相模仿，影子也跟着歪歪扭扭的。',companionReply:'「算了算了，我们俩谁也别说谁。」',memory:'路灯下，和{name}互相学着走路，笑了一路。',stars:1,souvenir:''},
      '追着TA跑':{result:'你追上去，{name}笑得跑不动，扶着墙直喘。',companionReply:'「不跑了不跑了，你腿长我认输。」',memory:'巷子里追着{name}跑，TA笑着认了输。',stars:1,souvenir:''}
    }},
  {title:'给对方唱歌',
    scene:'回去的路上风很轻，街上的人渐渐少了。',
    companionAction:'{name}清了清嗓子，哼起一首很轻的调子。',
    companionLine:'「这首歌，是我最近最喜欢的，你听听。」',
    interactions:[{name:'认真听',playerAction:'你安静地听{name}哼完了一整段'},{name:'跟着哼',playerAction:'你也跟着哼起来，虽然有点跑调'}],
    outcomes:{
      '认真听':{result:'{name}哼得很轻，风把调子吹得断断续续的。',companionReply:'唱完{name}有点不好意思：「还行吗？」',memory:'晚风里，{name}哼了一首很轻的歌给你听。',stars:2,souvenir:''},
      '跟着哼':{result:'你跟了两句就跑调了，{name}被带得也跑调，最后两个人都笑了。',companionReply:'「不行了，你一带，我全忘了原调。」',memory:'你跟着{name}唱歌跑了调，把TA也带跑了。',stars:1,souvenir:''}
    }}
]);

// ==================== 3. 随机事件扩充（环境小事 +20）====================
JOURNEY_DB.random=JOURNEY_DB.random.concat([
  {title:'风送来的花香',
    scene:'走着走着，一阵风忽然送过来一股花香，说不清是什么花。',
    companionAction:'{name}停下脚步，吸了吸鼻子。',
    companionLine:'「好香……是从哪边吹来的？」',
    interactions:[{name:'顺着找',playerAction:'你们顺着风的方向找了一会儿，找到一棵开花的树'},{name:'记住这个味道',playerAction:'你深吸一口气，说要把这个味道记住'}],
    outcomes:{
      '顺着找':{result:'花香来自墙头探出来的一枝花，开得正盛。',companionReply:'{name}踮脚看了看：「是它，藏得还挺好。」',memory:'一阵风送来的花香，你们找到墙头那枝开得正盛的花。',stars:1,souvenir:''},
      '记住这个味道':{result:'你把那股花香记在了心里，像存下一小瓶风。',companionReply:'{name}说：「那以后闻到，就会想起这一天。」',memory:'风里的花香，被你们记成了一天的注脚。',stars:1,souvenir:''}
    }},
  {title:'巷口传来音乐',
    scene:'经过一条窄巷，巷口飘出一段旧歌，像从收音机里漏出来的。',
    companionAction:'{name}停下来听了一会儿。',
    companionLine:'「这首歌……我奶奶以前常放。」',
    interactions:[{name:'站住听完',playerAction:'你们站在巷口，把这首歌听完了'},{name:'循声找',playerAction:'你们往里走了走，看是谁在放歌'}],
    outcomes:{
      '站住听完':{result:'歌放完，巷口安静了一下，又响起下一首。',companionReply:'{name}说：「走吧，别打扰人家听歌。」',memory:'巷口漏出来的一段旧歌，和{name}站着听完了。',stars:1,souvenir:''},
      '循声找':{result:'声音来自巷子里一间亮着灯的旧店，老板趴在柜台打盹。',companionReply:'{name}放轻脚步：「嘘，他睡着了。」',memory:'巷口音乐来自一间打盹的旧店，你们悄悄走开了。',stars:1,souvenir:''}
    }},
  {title:'漂亮的窗户',
    scene:'一栋老楼二楼的窗户开着，窗台上摆着好几盆花。',
    companionAction:'{name}仰头看了一会儿。',
    companionLine:'「住在那个窗台后面的人，一定很会生活。」',
    interactions:[{name:'一起看',playerAction:'你们站在楼下，看了会儿那扇窗'},{name:'猜里面',playerAction:'你猜那扇窗后面是什么样的房间'}],
    outcomes:{
      '一起看':{result:'窗台的花在风里摆了摆，像在和你们打招呼。',companionReply:'{name}说：「它好像在跟我们挥手。」',memory:'一扇摆满花的窗户，和{name}站在楼下看了很久。',stars:1,souvenir:''},
      '猜里面':{result:'你们猜那扇窗后面是厨房还是书房，猜了半天也没定论。',companionReply:'{name}说：「那就当它是书房吧，光线那么好。」',memory:'和{name}猜了一扇窗户后面的房间。',stars:1,souvenir:''}
    }},
  {title:'特别的老树',
    scene:'街角长着一棵很老很老的树，树干上爬满青苔。',
    companionAction:'{name}伸手摸了摸树皮，粗糙得像皱起来的纸。',
    companionLine:'「这棵树，比我们所有人的岁数加起来都大。」',
    interactions:[{name:'抱一抱',playerAction:'你张开手臂，试着抱了抱那棵老树'},{name:'听TA讲',playerAction:'你问{name}，这棵树见过多少故事'}],
    outcomes:{
      '抱一抱':{result:'你抱到一半就抱不过来了，{name}在旁边笑得直拍手。',companionReply:'「行了行了，你抱不下的，它原谅你了。」',memory:'你试着抱一棵很老很老的树，抱不过来。',stars:1,souvenir:''},
      '听TA讲':{result:'{name}说这棵树见过很多人路过，见过树叶黄了又绿。',companionReply:'「我们也是它见过的人里的一个。」',memory:'老树下，{name}说这棵树见过很多人，也包括你们。',stars:2,souvenir:''}
    }},
  {title:'彩虹泡泡',
    scene:'路边有个小孩在吹泡泡，阳光把泡泡染成彩色。',
    companionAction:'{name}伸手，让一个泡泡落在手心里，轻轻地破了。',
    companionLine:'「你看，泡泡上真的有彩虹。」',
    interactions:[{name:'一起吹',playerAction:'你也买了一管泡泡，和{name}一起吹'},{name:'追泡泡',playerAction:'你伸手去追一个飞远的泡泡'}],
    outcomes:{
      '一起吹':{result:'你们吹出一串泡泡，风把它们带走，像一群彩色的小鱼。',companionReply:'{name}说：「好像把一段路都吹成童话了。」',memory:'路边吹了一串彩色泡泡，{name}说这段路像童话。',stars:1,souvenir:''},
      '追泡泡':{result:'你追的那个泡泡在半空破了，{name}说你动作太慢。',companionReply:'「算了，我再给你吹一个。」',memory:'你追着泡泡跑，{name}说再给你吹一个。',stars:1,souvenir:''}
    }},
  {title:'落叶堆',
    scene:'人行道边堆着一小堆落叶，风一来就打着转。',
    companionAction:'{name}捧起一把落叶，往上一扬。',
    companionLine:'「你看，像不像下了一场黄叶雨？」',
    interactions:[{name:'一起扬',playerAction:'你也捧起一把落叶，和{name}一起扬'},{name:'挑一片好看的',playerAction:'你在落叶堆里挑了一片形状好看的'}],
    outcomes:{
      '一起扬':{result:'黄叶雨落下来，落得你们满头满肩都是。',companionReply:'{name}抖抖头发：「拍一拍，别把秋天带回家了。」',memory:'路边扬起的落叶雨，落了你们一头。',stars:1,souvenir:''},
      '挑一片好看的':{result:'你挑了一片边缘完整的叶子，{name}看了看说可以当书签。',companionReply:'「回去压一压，就是一片秋天的书签。」',memory:'你在落叶堆里挑了一片好看的叶子。',stars:1,souvenir:'🍂 秋天书签'}
    }},
  {title:'路灯下的小摊',
    scene:'路灯下面摆着一个小摊，摊主正支起一盏更亮的灯。',
    companionAction:'{name}在小摊前停下来，看摊上的小玩意儿。',
    companionLine:'「晚上摆摊的，卖的好像都是白天看不到的东西。」',
    interactions:[{name:'逛逛',playerAction:'你在摊子上看了看，都是些手工的小物件'},{name:'买一样',playerAction:'你挑了一样小东西，问摊主价格'}],
    outcomes:{
      '逛逛':{result:'摊上有手工的布包、编的绳子，还有几串旧钥匙。',companionReply:'{name}说：「每一件都像有自己的来历。」',memory:'路灯下的小摊，和{name}逛了一圈手作小物。',stars:1,souvenir:''},
      '买一样':{result:'你买了一枚手工编的绳结，摊主说戴在手上会带来好运。',companionReply:'{name}看着你系上：「那它现在要管我们两个人的好运了。」',memory:'路灯下的小摊，你买了一枚编绳结，说要带来好运。',stars:2,souvenir:'🧵 编绳结'}
    }},
  {title:'报纸被风吹走',
    scene:'一张报纸被风卷起来，贴着地面飞了一段，落在你们脚边。',
    companionAction:'{name}弯腰捡起来，抖了抖灰。',
    companionLine:'「是今天的报纸，你看，还写着一家老店要关门了。」',
    interactions:[{name:'看看报纸',playerAction:'你们一起看了报纸上的新闻'},{name:'放回路边',playerAction:'你把报纸折好，放回路边的长椅上'}],
    outcomes:{
      '看看报纸':{result:'报纸上印着陌生的城市新闻，日期是今天。',companionReply:'{name}说：「我们离开的这些天，这座城市也在过日子。」',memory:'被风吹来的报纸，和{name}一起看了陌生的城市新闻。',stars:1,souvenir:''},
      '放回路边':{result:'你把报纸折好放回长椅，像替它找到了位置。',companionReply:'{name}说：「下一个路过的人，也许会坐下来读。」',memory:'你把风里捡来的报纸折好，放回了长椅上。',stars:1,souvenir:''}
    }},
  {title:'冰淇淋车',
    scene:'远处传来一段叮叮当当的音乐，一辆冰淇淋车正慢慢开过来。',
    companionAction:'{name}看着冰淇淋车开近，眼睛跟着亮起来。',
    companionLine:'「是冰淇淋车！这个必须拦下来。」',
    interactions:[{name:'招手拦车',playerAction:'你冲冰淇淋车招手，车缓缓停在你面前'},{name:'让TA去',playerAction:'你推了推{name}，让TA去买'}],
    outcomes:{
      '招手拦车':{result:'你买了两个甜筒，一个香草一个草莓，递了一个给{name}。',companionReply:'{name}接过去：「你怎么知道我喜欢草莓的。」',memory:'路边拦下一辆冰淇淋车，买了两个甜筒。',stars:1,souvenir:'🍦 草莓甜筒'},
      '让TA去':{result:'{name}跑过去又跑回来，举着两个甜筒，跑得有点喘。',companionReply:'「给，你的那份，我挑了最圆的那个。」',memory:'{name}跑去冰淇淋车买了两个甜筒，说给你挑了最圆的。',stars:1,souvenir:''}
    }},
  {title:'街头艺人',
    scene:'广场一角，一个艺人正拉着一把旧提琴，曲子很熟。',
    companionAction:'{name}在琴盒前站定，安静地听完了一整段。',
    companionLine:'「拉得真好……我们放一点零钱吧。」',
    interactions:[{name:'放零钱',playerAction:'你往琴盒里放了几枚硬币，艺人朝你点了点头'},{name:'站着听',playerAction:'你们站着，把整支曲子听完了'}],
    outcomes:{
      '放零钱':{result:'硬币落进琴盒，艺人没停下，只是朝你们的方向点了点头。',companionReply:'{name}小声说：「这样他就知道有人喜欢了。」',memory:'广场上，你往提琴艺人的琴盒里放了零钱。',stars:1,souvenir:''},
      '站着听':{result:'曲子拉完，艺人朝你们笑了笑，又拉起下一首。',companionReply:'{name}说：「再听一首，就当是今天的主题曲。」',memory:'广场上，和{name}听完了一整支提琴曲。',stars:1,souvenir:''}
    }},
  {title:'天上的云',
    scene:'头顶的云很轻，被风扯成一条一条的，像鱼鳞。',
    companionAction:'{name}仰着头走了一段，差点撞上路灯。',
    companionLine:'「你看那片云，像不像一只在游的鲸鱼？」',
    interactions:[{name:'一起看云',playerAction:'你们边走边抬头，看云慢慢变形状'},{name:'比谁看得多',playerAction:'你提议比赛，看谁先找出十种云的形状'}],
    outcomes:{
      '一起看云':{result:'云从鲸鱼变成了帆船，又散成一片羽毛。',companionReply:'{name}说：「云的形状，只有抬头的人看得到。」',memory:'和{name}一起看云，从鲸鱼看到羽毛。',stars:1,souvenir:''},
      '比谁看得多':{result:'你们一路数到九种形状，最后谁也凑不齐十种，打了个平手。',companionReply:'{name}说：「第九种算半只，再找半只就平了。」',memory:'和{name}比着数云的形状，数到九种打了个平手。',stars:1,souvenir:''}
    }},
  {title:'寺庙的钟声',
    scene:'远处传来一阵悠长的钟声，一下一下，穿过整条街。',
    companionAction:'{name}停下脚步，闭了一下眼。',
    companionLine:'「这个声音……好像能把心里的乱东西都震掉。」',
    interactions:[{name:'静静听',playerAction:'你们站在路边，把钟声听完'},{name:'寻声去',playerAction:'你们顺着钟声的方向走了一段，看到远处的寺檐'}],
    outcomes:{
      '静静听':{result:'钟声一下一下地响，街上的人好像都慢了半拍。',companionReply:'{name}睁开眼：「好了，听完了，心里干净了。」',memory:'一阵钟声穿过整条街，和{name}站在路边听完了。',stars:1,souvenir:''},
      '寻声去':{result:'寺檐在远处露出一角，钟声正是从那里传来的。',companionReply:'{name}说：「看一眼就好，不用进去。」',memory:'顺着钟声的方向，看到了远处的寺檐。',stars:1,souvenir:''}
    }},
  {title:'河边的鸭子',
    scene:'河岸边，几只鸭子排着队从水里上岸，慢悠悠地踱步。',
    companionAction:'{name}蹲下来，看着鸭子们摇摇摆摆地走过。',
    companionLine:'「你看它们，走路的架势像在巡视自己的地盘。」',
    interactions:[{name:'一起看',playerAction:'你们蹲在岸边，看鸭子们一只一只走远'},{name:'学鸭子走',playerAction:'你学着鸭子走路，{name}在旁边憋着笑'}],
    outcomes:{
      '一起看':{result:'鸭子们走到草坡上，一起回头看了看河面，又继续走。',companionReply:'{name}说：「它们好像有固定的路线。」',memory:'河岸边，和{name}看鸭子们排队巡河。',stars:1,souvenir:''},
      '学鸭子走':{result:'你学得惟妙惟肖，{name}终于没憋住，笑出了声。',companionReply:'「你学鸭子比鸭子还像鸭子。」',memory:'你学鸭子走路，把{name}逗笑了。',stars:1,souvenir:''}
    }},
  {title:'树洞里的字条',
    scene:'一棵老树的树洞里，塞着一张折起来的纸，露出一个角。',
    companionAction:'{name}小心地抽出来，展开看了一眼。',
    companionLine:'「上面写着：『如果你看到这张纸，今天要开心。』」',
    interactions:[{name:'留一张回去',playerAction:'你也写了一张字条，塞回树洞里'},{name:'放回去',playerAction:'你把字条折好，小心地放回原处'}],
    outcomes:{
      '留一张回去':{result:'你在字条上写「看到了，今天很开心」，叠好塞回树洞。',companionReply:'{name}说：「那下一个人，会连着看到两份祝福。」',memory:'树洞里的字条，你写了回信塞回去，像完成了一次接力。',stars:2,souvenir:''},
      '放回去':{result:'你把字条折好放回树洞，像替那个陌生人藏好秘密。',companionReply:'{name}说：「我们算是替它保守了秘密。」',memory:'发现树洞里有一张叫你要开心的字条，你们又放了回去。',stars:1,souvenir:''}
    }},
  {title:'雨后水洼',
    condition:'雨天',
    scene:'雨停后，路面留下一个个亮晶晶的小水洼。',
    companionAction:'{name}踩过一个水洼，水花溅起来，亮了一下。',
    companionLine:'「你看，踩水洼是下雨天唯一的好处。」',
    interactions:[{name:'一起踩',playerAction:'你和{name}一起踩着水洼往前走'},{name:'看倒影',playerAction:'你蹲下来，看水洼里倒着的那片天'}],
    outcomes:{
      '一起踩':{result:'水洼被你们踩出一路水花，裤脚全湿了也顾不上。',companionReply:'{name}笑着说：「鞋都湿了，值了。」',memory:'雨后水洼，和{name}踩出一路水花，鞋都湿了。',stars:1,souvenir:''},
      '看倒影':{result:'水洼里倒着半边天和一朵云，像另一个小小的世界。',companionReply:'{name}也蹲下来：「这个角度，天空就在脚下。」',memory:'雨后水洼里倒着整片天，和{name}蹲着看了半天。',stars:1,souvenir:''}
    }},
  {title:'便利店的新品',
    scene:'路过便利店，玻璃门上贴着「本周新品」的海报。',
    companionAction:'{name}在货架前挑了半天，拿起一包看着眼生的零食。',
    companionLine:'「这个口味没见过，要不要试试？踩雷了我请。」',
    interactions:[{name:'试试',playerAction:'你买了一包新品，和{name}一人一块拆开来尝'},{name:'猜口味',playerAction:'你们先猜了猜这个口味是什么样的'}],
    outcomes:{
      '试试':{result:'味道意外地不错，你们又回去买了两包。',companionReply:'{name}得意：「我挑东西的眼光一向准。」',memory:'便利店的新品零食，意外地好吃，你们回购了两包。',stars:1,souvenir:''},
      '猜口味':{result:'猜了半天没猜对，拆开一尝，是种说不清但还不错的口味。',companionReply:'{name}说：「猜不对也没关系，好吃就行。」',memory:'便利店门口，和{name}猜了一包新口味零食的味道。',stars:1,souvenir:''}
    }},
  {title:'夕阳下的长椅',
    scene:'公园边一张长椅正好迎着夕阳，椅面被晒得暖烘烘的。',
    companionAction:'{name}走过去坐下，拍了拍身边。',
    companionLine:'「坐一下吧，这个位置，太阳刚好不晒。」',
    interactions:[{name:'坐下',playerAction:'你在{name}旁边坐下，一起看夕阳'},{name:'站着挡光',playerAction:'你站着，正好替{name}挡住斜过来的光'}],
    outcomes:{
      '坐下':{result:'夕阳把你们的影子拉得很长，一直伸到草坪那头。',companionReply:'{name}说：「这个长椅，以后就是我们的了。」',memory:'夕阳下的长椅，和{name}坐着看影子越拉越长。',stars:2,souvenir:''},
      '站着挡光':{result:'你站在{name}和夕阳中间，光从你身后绕过来。',companionReply:'{name}仰头看你：「你还挺会挡光的。」',memory:'夕阳下，你站着替{name}挡住了一束光。',stars:1,souvenir:''}
    }},
  {title:'地图上的小惊喜',
    scene:'路边立着一块旅游地图，图上标着几个星号。',
    companionAction:'{name}凑到地图前，指着其中一个星号。',
    companionLine:'「这里标着『秘密花园』，地图上才有的地方。」',
    interactions:[{name:'去探一探',playerAction:'你们照着地图，去找那个秘密花园'},{name:'记下来',playerAction:'你们把位置记下来，打算明天去'}],
    outcomes:{
      '去探一探':{result:'地图上标的地方其实是一片小空地，种着几棵桂花树。',companionReply:'{name}说：「是不是秘密花园？是。」',memory:'按地图找到的"秘密花园"，其实是几棵桂花树。',stars:2,souvenir:''},
      '记下来':{result:'你们在手机地图上打了个星标，把惊喜留给了明天。',companionReply:'{name}说：「有期待，明天就有奔头。」',memory:'地图上的"秘密花园"，你们打了个星标留到明天。',stars:1,souvenir:''}
    }}
]);

// ==================== 4. 环境事件（无选择，直接经历）====================
var JOURNEY_AMBIENT=[
  {title:'一场不急的雨',
    condition:'雨天',
    scene:'雨细细地落下来，不急不慢，像在替天空扫地。',
    companionAction:'{name}伸出手，接了几滴雨，看着它们在手心聚成一小洼。',
    companionLine:'「这种雨最好了，下不大，也停不了，刚好配慢走。」',
    memory:'一场不急的雨里，和{name}慢慢走了很长一段路。',stars:1},
  {title:'风把路边的花吹低了',
    scene:'风一阵阵吹过，路边的花被压弯又弹起来，像在鞠躬。',
    companionAction:'{name}放慢脚步，学着花的样子弯了弯腰。',
    companionLine:'「你看，它们好像在说欢迎光临。」',
    memory:'风把路边的花吹得弯弯腰，{name}也学着弯了弯。',stars:1},
  {title:'天忽然蓝得不像话',
    scene:'云一下子全散开了，天空蓝得像刚洗过。',
    companionAction:'{name}停下来，仰着头看了好一会儿。',
    companionLine:'「这种蓝，一年也见不到几次。」',
    memory:'天空忽然蓝得不像话，和{name}一起仰头看了很久。',stars:1},
  {title:'树影在墙上画画',
    scene:'阳光穿过树叶，在墙上投下晃动的影子，像一幅会动的画。',
    companionAction:'{name}伸手在墙上比了比，影子里多出一只手。',
    companionLine:'「你看，我们也在画里了。」',
    memory:'阳光把树影画在墙上，{name}说你们也进了画里。',stars:1},
  {title:'一个陌生的微笑',
    scene:'对面走过来一个老人，看见你们，笑了笑，什么都没说。',
    companionAction:'{name}愣了一下，也回了一个笑。',
    companionLine:'「不知道为什么，收到一个陌生的笑，心情好了很多。」',
    memory:'路上收到一个陌生人的微笑，{name}说心情好了很多。',stars:1},
  {title:'麻雀在脚边跳',
    scene:'几只麻雀在脚边跳来跳去，也不怕人，啄着地上的碎屑。',
    companionAction:'{name}放轻脚步，小心地绕开它们。',
    companionLine:'「别踩到它们，它们在吃午饭呢。」',
    memory:'几只不怕人的麻雀在脚边跳，你们小心地绕开了。',stars:1},
  {title:'巷子里飘出饭菜香',
    scene:'傍晚的巷子里，飘出几户人家的饭菜香，混在一起。',
    companionAction:'{name}吸了吸鼻子，眼睛眯起来。',
    companionLine:'「有红烧肉的味道……还有番茄炒蛋。」',
    memory:'傍晚的巷子里，和{name}猜了一路别人家的晚饭。',stars:1},
  {title:'一片梧桐叶落下来',
    scene:'一片梧桐叶打着旋，不偏不倚，落在{name}的肩膀上。',
    companionAction:'{name}低头看了看，没摘，让叶子在肩头待着。',
    companionLine:'「先留着，说不定是什么好兆头。」',
    memory:'一片梧桐叶落在{name}肩头，TA说留着当好运。',stars:1,souvenir:'🍁 肩头的落叶'},
  {title:'远处的钟楼报时',
    scene:'整点的时候，远处的钟楼响了一声，很轻，却传得很远。',
    companionAction:'{name}停下脚步，侧耳听了一下。',
    companionLine:'「这个时间，我们刚好走到这里，也算一种巧合。」',
    memory:'钟楼报时的那一刻，你们刚好走到那条路上。',stars:1},
  {title:'路灯次第亮起来',
    scene:'天色暗下来，路灯一盏接一盏地亮起，像有人沿路点灯。',
    companionAction:'{name}看着路灯亮到眼前，忽然笑了。',
    companionLine:'「好像有人知道我们在走路，提前把灯点亮了。」',
    memory:'路灯次第亮起来，{name}说像有人替你们点了灯。',stars:1},
  {title:'河面起了薄雾',
    scene:'河面上浮着一层薄薄的雾，对岸的房子像隔了一层纱。',
    companionAction:'{name}扶着栏杆看了一会儿，没说话。',
    companionLine:'过了很久，TA轻声说：「雾散了，这边更好看。」',
    memory:'河面的薄雾里，{name}说雾散了这边更好看。',stars:1},
  {title:'一只蜻蜓停在水草上',
    scene:'河边的水草上，一只蜻蜓停着，翅膀在光里闪着蓝绿色。',
    companionAction:'{name}凑近看了看，又慢慢退回来。',
    companionLine:'「别碰它，让它多停一会儿。」',
    memory:'一只蜻蜓停在河边水草上，你们安静地看了一会儿。',stars:1},
  {title:'黄昏的风忽然暖起来',
    scene:'傍晚的风忽然变暖了，带着白天太阳的余温。',
    companionAction:'{name}张开手掌，感受了一下风。',
    companionLine:'「这股风，是白天攒下来的，现在都还给我们了。」',
    memory:'黄昏的暖风，{name}说那是白天攒下来的阳光。',stars:1},
  {title:'云把月亮遮了一半',
    condition:'夜晚',
    scene:'夜空中，一片薄云飘过来，把月亮遮了一半。',
    companionAction:'{name}仰着头，等云慢慢飘过去。',
    companionLine:'「你看，月亮在跟云玩捉迷藏。」',
    memory:'夜晚的云把月亮遮了一半，和{name}看它慢慢露出来。',stars:1},
  {title:'街角的老式理发店',
    scene:'街角有家老式理发店，玻璃门上贴着褪色的广告，灯还亮着。',
    companionAction:'{name}趴在玻璃门外看了看里面。',
    companionLine:'「这种店，现在很少见了，感觉进去能剪回二十年前。」',
    memory:'街角的老式理发店，{name}说进去能剪回二十年前。',stars:1},
  {title:'一阵风把帽沿吹歪',
    scene:'风忽然大了一下，把{name}的帽沿吹得歪向一边。',
    companionAction:'{name}扶了扶帽子，又故意让风把它吹歪。',
    companionLine:'「算了，让它歪着吧，这样也挺好看。」',
    memory:'一阵风把{name}的帽沿吹歪，TA干脆让它歪着。',stars:1},
  {title:'书店门口的木牌',
    scene:'一家小书店门口挂着一块手写的木牌：今日推荐《慢一点》。',
    companionAction:'{name}念出书名，两个人同时笑了。',
    companionLine:'「这本书，我们今天正在读。」',
    memory:'书店门口的木牌写着《慢一点》，{name}说你们正在读。',stars:1},
  {title:'雨把玻璃窗洗了一遍',
    condition:'雨天',
    scene:'雨点打在沿街的玻璃窗上，把灰蒙蒙的窗户洗得透亮。',
    companionAction:'{name}隔着玻璃往里看了看，又看到自己倒影，愣了一下。',
    companionLine:'「雨停之前，这扇窗里的世界比外面清楚。」',
    memory:'雨把沿街的玻璃窗洗干净了，{name}对着倒影愣了一下。',stars:1},
  {title:'云缝里漏下一束光',
    scene:'厚重的云层忽然裂开一道缝，一束阳光笔直地漏下来。',
    companionAction:'{name}指着那束光，声音都轻了。',
    companionLine:'「你看，像不像舞台上追着人的那束光。」',
    memory:'云缝里漏下一束光，{name}说像舞台上的追光。',stars:2},
  {title:'路过一群放学的小孩',
    scene:'一群小孩背着书包跑过，书包在背后一跳一跳的，笑声很响。',
    companionAction:'{name}看着他们跑远，眼神有点怀念。',
    companionLine:'「以前放学的时候，我们也这样跑过吧。」',
    memory:'路过一群放学的小孩，{name}说以前也这样跑过。',stars:1}
];

// ==================== 5. 多人互动（≥2 名梦角同行时出现）====================
// {m0}/{m1} 按同行梦角顺序替换；members[].action/line 依次渲染对话气泡
var JOURNEY_MULTI=[
  {title:'最后一块蛋糕',
    scene:'甜品店的橱窗里，只剩最后一块蛋糕，灯光把它照得发亮。',
    members:[
      {action:'{m0}看了一眼那块蛋糕，又看了一眼你。',line:'「只剩一块了。」'},
      {action:'{m1}也凑过来，盯着那块蛋糕看了两秒。',line:'「我也想吃。」'}
    ],
    companionAction:'两个人同时把目光转向你。',
    companionLine:'「你来决定。」',
    interactions:[{name:'给{m0}',playerAction:'你说最后一块给{m0}'},{name:'给{m1}',playerAction:'你说最后一块给{m1}'},{name:'分成三份',playerAction:'你让店员把蛋糕切成三份'}],
    outcomes:{
      '给{m0}':{result:'{m0}接过蛋糕，看了看{m1}，掰了一半递过去。',companionReply:'「一起吃吧，一个人吃没意思。」',memory:'最后一块蛋糕，{m0}自己掰了一半分给了{m1}。',stars:2,souvenir:''},
      '给{m1}':{result:'{m1}拿着蛋糕，先举到你面前：「你先尝第一口。」',companionReply:'「第一口给决定的人。」',memory:'最后一块蛋糕，{m1}让你先尝了第一口。',stars:2,souvenir:''},
      '分成三份':{result:'店员把蛋糕切成三份，你们一人一份，谁也没多谁也没少。',companionReply:'{m0}说：「这样最好，谁也别馋谁。」',memory:'一块蛋糕分成三份，你们吃得谁也不欠谁。',stars:1,souvenir:''}
    }},
  {title:'争论走哪条路',
    scene:'岔路口，两个方向的风景看起来都很好。',
    members:[
      {action:'{m0}指着左边。',line:'「走这边，这边有树荫。」'},
      {action:'{m1}指着右边。',line:'「走那边，那边能看到河。」'}
    ],
    companionAction:'两个人谁也不让谁，一起转头看你。',
    companionLine:'「你说，听谁的？」',
    interactions:[{name:'听{m0}的',playerAction:'你选了左边有树荫的路'},{name:'听{m1}的',playerAction:'你选了右边能看到河的路'},{name:'让TA们自己定',playerAction:'你说让两个人石头剪刀布决定'}],
    outcomes:{
      '听{m0}的':{result:'树荫下的路很凉快，走了一会儿，{m1}也不吵了。',companionReply:'{m1}说：「行吧，树荫确实不错。」',memory:'岔路口，你选了{m0}的路，后来{m1}也承认不错。',stars:1,souvenir:''},
      '听{m1}的':{result:'河边的路风很大，能看到整条河，{m0}也点了点头。',companionReply:'{m0}说：「嗯……河是挺好看的。」',memory:'岔路口，你选了能看到河的路，{m0}也服气了。',stars:1,souvenir:''},
      '让TA们自己定':{result:'两个人石头剪刀布，{m0}赢了，{m1}愿赌服输，跟了上来。',companionReply:'{m1}小声说：「下次我一定赢。」',memory:'岔路口，你让两个人石头剪刀布，{m0}赢了。',stars:1,souvenir:''}
    }},
  {title:'谁先发现彩虹糖',
    scene:'路边的小摊上摆着一罐彩虹色的糖，颜色很晃眼。',
    members:[
      {action:'{m0}先看到了，指给你看。',line:'「那个糖，颜色好漂亮。」'},
      {action:'{m1}已经走到摊前了。',line:'「买一罐吧，一人分几颗。」'}
    ],
    companionAction:'两个人站在摊前，等着你拿主意。',
    companionLine:'「买不买？买的话怎么分？」',
    interactions:[{name:'买来分',playerAction:'你买了一罐，三个人分了'},{name:'让TA们选口味',playerAction:'你说让两个人各挑喜欢的颜色'},{name:'不买，看看就走',playerAction:'你说看看就好，留着钱吃正餐'}],
    outcomes:{
      '买来分':{result:'一罐彩虹糖分成了三份，有人挑红的，有人挑蓝的。',companionReply:'{m0}数着自己的：「我挑到了七颗，我赢。」',memory:'一罐彩虹糖分成三份，三个人数着谁的颗数多。',stars:1,souvenir:'🌈 彩虹糖'},
      '让TA们选口味':{result:'{m0}选了绿色，{m1}选了紫色，剩下黄的都归你。',companionReply:'{m1}说：「黄色是快乐的颜色，让给你。」',memory:'彩虹糖，{m0}选绿色，{m1}选紫色，黄色都归你。',stars:1,souvenir:''},
      '不买，看看就走':{result:'你们看看那罐糖，又看了看彼此的牙，笑着走了。',companionReply:'{m0}说：「也对，明天还得见人。」',memory:'三个人路过彩虹糖，互相看了看，笑着走开了。',stars:1,souvenir:''}
    }},
  {title:'三个人的影子',
    scene:'夕阳西下，你们三个人在路上的影子被拉得很长，叠在一起。',
    members:[
      {action:'{m0}低头看着影子。',line:'「我们的影子叠在一起了。」'},
      {action:'{m1}动了动脚，影子也跟着动。',line:'「像三个牵着手的小人。」'}
    ],
    companionAction:'三个人故意把影子踩在一起，又分开。',
    companionLine:'「这样就像真的手牵手了。」',
    interactions:[{name:'牵起手',playerAction:'你伸手，三个人真的牵起了手'},{name:'比影子',playerAction:'你们举起手，在影子里比出各种形状'}],
    outcomes:{
      '牵起手':{result:'三个人牵着手走了几步，又不好意思地松开，都笑了。',companionReply:'{m1}说：「刚才那几步，影子里是牵着手的。」',memory:'夕阳下，三个人真的牵着手走了几步。',stars:2,souvenir:''},
      '比影子':{result:'影子里伸出三只手，比出了三只不同的动物。',companionReply:'{m0}说：「看，我们的动物园。」',memory:'夕阳下，三个人的影子比出了一个动物园。',stars:1,souvenir:''}
    }},
  {title:'纪念品店的选择困难',
    scene:'纪念品店里的冰箱贴铺了一整面墙，看得人眼花。',
    members:[
      {action:'{m0}拿起一个又放下。',line:'「每一个都好看，怎么办。」'},
      {action:'{m1}直接挑了三个。',line:'「都买，回去慢慢挑。」'}
    ],
    companionAction:'两个人齐刷刷看着你。',
    companionLine:'「你选一个？我们仨正好一人一个不同的。」',
    interactions:[{name:'选一个',playerAction:'你从墙上挑了一个最喜欢的冰箱贴'},{name:'让TA们先选',playerAction:'你说让两个人先选，剩下的归你'}],
    outcomes:{
      '选一个':{result:'你挑的是一个画着当地风景的，{m0}挑了房子，{m1}挑了猫。',companionReply:'{m1}说：「回去贴在冰箱上，能凑出一趟旅行。」',memory:'三个人各挑了一个冰箱贴，说能凑出一趟旅行。',stars:2,souvenir:'🧲 风景冰箱贴'},
      '让TA们先选':{result:'{m0}挑了风景，{m1}挑了猫咪，剩下的那个是只歪歪的小船。',companionReply:'{m0}说：「小船好看，留给你的最好。」',memory:'纪念品店，你让两个人先选，剩下的那只小船归你。',stars:1,souvenir:''}
    }},
  {title:'晚上的夜宵之争',
    scene:'天黑下来，三个人在夜市的香气里走不动道。',
    members:[
      {action:'{m0}被烧烤的烟味勾住了。',line:'「我想吃烧烤。」'},
      {action:'{m1}盯着隔壁的糖水铺。',line:'「我想喝糖水。」'}
    ],
    companionAction:'两个人一个看左边，一个看右边。',
    companionLine:'「你选，我们听你的。」',
    interactions:[{name:'吃烧烤',playerAction:'你选了烧烤摊'},{name:'喝糖水',playerAction:'你选了糖水铺'},{name:'先烧烤后糖水',playerAction:'你说先吃烧烤，再喝糖水，两全其美'}],
    outcomes:{
      '吃烧烤':{result:'烧烤摊前坐定，{m1}还是惦记糖水，你答应吃完再去。',companionReply:'{m1}说：「说好了，吃完这家去那家。」',memory:'夜市，你选了烧烤，{m1}惦记着糖水，说吃完再去。',stars:1,souvenir:''},
      '喝糖水':{result:'糖水端上来，{m0}喝了一口，眼睛亮了，说也不亏。',companionReply:'{m0}说：「行吧，糖水也挺好。」',memory:'夜市，你选了糖水，{m0}尝了一口也说好。',stars:1,souvenir:''},
      '先烧烤后糖水':{result:'你们先撸完烧烤，又去喝糖水，{m0}{m1}都心满意足。',companionReply:'{m1}摸着肚子：「今晚谁也别提减肥。」',memory:'夜市里，你们先吃烧烤再喝糖水，三个人都圆满了。',stars:2,souvenir:''}
    }},
  {title:'互相拍照',
    scene:'风景很好的地方，三个人都想拍下来。',
    members:[
      {action:'{m0}举着手机，指挥站位。',line:'「你们站过去，我拍一张。」'},
      {action:'{m1}已经摆好了姿势。',line:'「快点快点，笑要僵了。」'}
    ],
    companionAction:'两个人都把手机递向你。',
    companionLine:'「你拍，你最会拍了。」',
    interactions:[{name:'帮TA们拍',playerAction:'你接过手机，给两个人拍了一张'},{name:'三人合照',playerAction:'你找路人帮忙，三个人拍了张合照'}],
    outcomes:{
      '帮TA们拍':{result:'照片里两个人站得有点远，你喊了一声「靠近一点」，她们才挪了挪。',companionReply:'{m1}看着照片：「这张可以，发群里。」',memory:'风景前，你给{m0}和{m1}拍了一张照片。',stars:1,souvenir:''},
      '三人合照':{result:'路人帮你们拍的合照里，三个人的笑都有点傻，但很真。',companionReply:'{m0}说：「这张以后可以挂墙上。」',memory:'风景前，你们三个人的第一张合照。',stars:2,souvenir:'📸 三人合照'}
    }},
  {title:'走丢了一只鞋带',
    scene:'走着走着，{m0}的鞋带散了，自己还没发现。',
    members:[
      {action:'{m1}先看到，喊了一声。',line:'「你鞋带散了！」'},
      {action:'{m0}低头看了看，不好意思。',line:'「啊，谢谢，差点绊倒。」'}
    ],
    companionAction:'两个人一个蹲下系鞋带，一个在旁边等着。',
    companionLine:'「你系你的，我们等你。」',
    interactions:[{name:'帮TA系',playerAction:'你蹲下来，帮{m0}把鞋带重新系好'},{name:'递个东西垫脚',playerAction:'你找了块干净的地方，让{m0}坐着系'}],
    outcomes:{
      '帮TA系':{result:'你系好鞋带抬头，{m0}愣了一下，小声说了句谢谢。',companionReply:'{m1}在旁边：「哇，服务还挺周到。」',memory:'{m0}的鞋带散了，你蹲下来帮TA系好了。',stars:2,souvenir:''},
      '递个东西垫脚':{result:'{m0}坐在台阶上系好鞋带，站起来拍了拍手：「继续走！」',companionReply:'{m1}说：「系个鞋带还要找座位，讲究。」',memory:'{m0}系鞋带，你找了台阶给TA坐，{m1}笑TA讲究。',stars:1,souvenir:''}
    }},
  {title:'三个人的秋千',
    scene:'公园里只有一架秋千，被三个人看见了。',
    members:[
      {action:'{m0}先跑过去占了位置。',line:'「我先坐！你们排队。」'},
      {action:'{m1}不紧不慢。',line:'「那我第二个。」'}
    ],
    companionAction:'两个人一起回头看你。',
    companionLine:'「你排第几？」',
    interactions:[{name:'让TA们先玩',playerAction:'你说你最后，让两个人先荡'},{name:'抢第三个位置',playerAction:'你说秋千只有一架，但你可以推'}],
    outcomes:{
      '让TA们先玩':{result:'{m0}荡完{m1}荡，你在旁边推，两个人玩得顾不上你。',companionReply:'{m0}下来的时候说：「该你了，我给你推。」',memory:'公园的秋千，你让两个人先玩，最后TA们给你推。',stars:1,souvenir:''},
      '抢第三个位置':{result:'你说你负责推，两个人轮流荡，一下午就这么过去了。',companionReply:'{m1}说：「这个安排，三个人都开心。」',memory:'一架秋千，你推，两个人荡，谁也没落下。',stars:2,souvenir:''}
    }},
  {title:'谁最会讲价',
    scene:'小摊前，你们看中了一样东西，摊主报了价。',
    members:[
      {action:'{m0}试着还了个价。',line:'「老板，便宜点嘛。」'},
      {action:'{m1}在旁边帮腔。',line:'「对啊，我们三个人一起买呢。」'}
    ],
    companionAction:'两个人一起看向你。',
    companionLine:'「你也帮两句，三人成虎。」',
    interactions:[{name:'一起砍价',playerAction:'你也加入，三个人你一句我一句'},{name:'直接买',playerAction:'你说算了，喜欢就买，别砍了'}],
    outcomes:{
      '一起砍价':{result:'摊主被你们说得招架不住，最后抹了个零，皆大欢喜。',companionReply:'{m0}得意：「看到了吧，团结就是力量。」',memory:'小摊前，三个人一起砍价，摊主招架不住抹了零。',stars:1,souvenir:''},
      '直接买':{result:'你付了钱，{m0}和{m1}有点遗憾，但东西确实喜欢。',companionReply:'{m1}说：「行吧，你爽快，我们学着点。」',memory:'小摊前，你爽快地买下了东西，两个人说学着点。',stars:1,souvenir:''}
    }},
  {title:'雨天的一把伞',
    condition:'雨天',
    scene:'雨忽然下起来，你们三个人只有一把伞。',
    members:[
      {action:'{m0}撑开伞，举到头顶。',line:'「三个人一把伞，怎么分？」'},
      {action:'{m1}看了看你。',line:'「挤一挤？」'}
    ],
    companionAction:'伞下挤着两个人，还留了个位置。',
    companionLine:'「进来，三个人挤一挤，雨不大。」',
    interactions:[{name:'挤进去',playerAction:'你钻进伞下，三个人挤在一起走'},{name:'跑着走',playerAction:'你说你们撑伞，你跑着跟'},{name:'再买一把',playerAction:'你跑进旁边的小店，又买了一把伞'}],
    outcomes:{
      '挤进去':{result:'三个人挤在一把伞下，肩膀挨着肩膀，走得很慢。',companionReply:'{m1}说：「挤是挤了点，但挺暖和的。」',memory:'一把伞下挤着三个人，雨声里谁也没淋湿。',stars:2,souvenir:''},
      '跑着走':{result:'你在雨里小跑，两个人在伞下喊你：「进来！」你还是跑了半条街。',companionReply:'{m0}说：「下次不许跑了，三个人挤一挤刚好。」',memory:'雨天你跑着跟，被两个人喊了好几次「进来」。',stars:1,souvenir:''},
      '再买一把':{result:'你举着新伞跑回来，两把伞并排，谁也不用挤。',companionReply:'{m0}说：「还是你周到。」',memory:'雨天你跑去买了第二把伞，三个人都不用挤了。',stars:2,souvenir:'☂️ 第二把伞'}
    }},
  {title:'谁先爬到观景台',
    scene:'一座小山丘顶上有个观景台，能看到整座城。',
    members:[
      {action:'{m0}已经迈开步子往上冲。',line:'「先到的人先看！」'},
      {action:'{m1}不慌不忙。',line:'「跑那么快，上去还得等我们。」'}
    ],
    companionAction:'两个人都看着你。',
    companionLine:'「你跟谁一队？」',
    interactions:[{name:'跟{m0}冲',playerAction:'你跟{m0}一起往上冲'},{name:'跟{m1}慢走',playerAction:'你陪着{m1}慢慢往上走'}],
    outcomes:{
      '跟{m0}冲':{result:'你们先到观景台，风很大，整座城在脚下铺开。',companionReply:'{m0}喘着气说：「值了，风景归我们先看。」',memory:'观景台上，你和{m0}先到，把整座城看在了脚下。',stars:2,souvenir:''},
      '跟{m1}慢走':{result:'你们慢慢走上去时，{m0}已经在上面等得直招手。',companionReply:'{m1}说：「你看，他也没跑出多远。」',memory:'观景台，你陪着{m1}慢走，{m0}在上面等你们。',stars:1,souvenir:''}
    }},
  {title:'互相起外号（多人版）',
    scene:'走了大半天的路，三个人都有点累了，话也变少了。',
    members:[
      {action:'{m0}忽然开口。',line:'「你们俩，一个走路带风，一个总慢半拍。」'},
      {action:'{m1}回了一句。',line:'「那你呢，你像带路向导。」'}
    ],
    companionAction:'两个人同时看向你。',
    companionLine:'「轮到你评价我们俩了。」',
    interactions:[{name:'给TA们起外号',playerAction:'你给两个人各起了一个外号'},{name:'让TA们给你起',playerAction:'你说让两个人合伙给你起一个'}],
    outcomes:{
      '给TA们起外号':{result:'你叫{m0}「风火轮」，叫{m1}「慢慢来」，两个人居然都接受了。',companionReply:'{m0}说：「风火轮可以，比带路向导强。」',memory:'三个人互相起外号，你叫出了「风火轮」和「慢慢来」。',stars:1,souvenir:''},
      '让TA们给你起':{result:'两个人商量了半天，最后叫你好评师，因为你总在夸路边的东西。',companionReply:'{m1}说：「好评师，满意你收到的外号吗？」',memory:'三个人互相起外号，你被叫成了「好评师」。',stars:1,souvenir:''}
    }},
  {title:'夕阳下的背影',
    scene:'回程的路上，夕阳把三个人的影子拉得很长。',
    members:[
      {action:'{m0}走在最前面，影子最长。',line:'「今天走得好远啊。」'},
      {action:'{m1}走在你旁边。',line:'「但明天还能走更远。」'}
    ],
    companionAction:'三个人放慢脚步，谁也没说话，只听见脚步声。',
    companionLine:'过了很久，{m0}轻声说：「这样的路，以后多走几次就好了。」',
    interactions:[{name:'答应下次再走',playerAction:'你说好啊，下次换一条路再走'},{name:'拍个背影',playerAction:'你举起手机，拍下三个人的背影'}],
    outcomes:{
      '答应下次再走':{result:'你答应的时候，{m0}和{m1}都回头看了你一眼，笑着点了点头。',companionReply:'{m1}说：「说好了，换一条路。」',memory:'夕阳下，三个人约好下次换一条路再一起走。',stars:2,souvenir:''},
      '拍个背影':{result:'照片里三个人的影子拖得很长，像一个完整的画面。',companionReply:'{m0}看着照片说：「这张，是这个下午最好的一张。」',memory:'夕阳下，你拍下了三个人的背影和长长的影子。',stars:2,souvenir:'📸 三个背影'}
    }},
  {title:'分享一袋橘子',
    scene:'路边有人卖刚摘的橘子，香气扑鼻。',
    members:[
      {action:'{m0}买了一大袋。',line:'「来，一人分几个。」'},
      {action:'{m1}接过橘子，掰开一个。',line:'「好甜，这趟值了。」'}
    ],
    companionAction:'三个人一人捧着一个橘子，边走边剥。',
    companionLine:'「这种时候，橘子皮的味道都是香的。」',
    interactions:[{name:'掰开分一半',playerAction:'你把自己那个掰成两半，分给两个人'},{name:'比谁剥得完整',playerAction:'你提议比赛，看谁剥出的橘子皮最完整'}],
    outcomes:{
      '掰开分一半':{result:'你那个橘子分成了两半，{m0}和{m1}接过去，说不用不用。',companionReply:'{m1}说：「你留着自己吃，我们还有呢。」',memory:'一袋橘子，你把自己那个掰开分给了两个人。',stars:1,souvenir:''},
      '比谁剥得完整':{result:'三个人各显神通，最后{m0}的橘子皮剥得像朵花。',companionReply:'{m0}得意：「看，手艺人。」',memory:'三个人比剥橘子，{m0}剥出了一朵花。',stars:1,souvenir:''}
    }},
  {title:'夜里的星星（三人版）',
    condition:'夜晚',
    scene:'夜里抬头，星星比想象中多，密密地铺了一整片天。',
    members:[
      {action:'{m0}仰着头数星星。',line:'「我数到二十八颗了。」'},
      {action:'{m1}打断。',line:'「你数的都是同一片，不算。」'}
    ],
    companionAction:'两个人一起看向你。',
    companionLine:'「你来当裁判，到底谁数得对？」',
    interactions:[{name:'帮{m0}',playerAction:'你说{m0}数得对'},{name:'帮{m1}',playerAction:'你说{m1}说得有道理'},{name:'都不帮',playerAction:'你说别数了，一起看就行'}],
    outcomes:{
      '帮{m0}':{result:'{m0}得意地看了{m1}一眼，{m1}不服气地继续数。',companionReply:'{m1}小声说：「裁判偏心。」',memory:'夜里数星星，你当了裁判，{m1}说裁判偏心。',stars:1,souvenir:''},
      '帮{m1}':{result:'{m1}满意地点头，{m0}低头继续数，嘴里嘟囔着「才不是」。',companionReply:'{m0}说：「那我换个地方数。」',memory:'夜里数星星，你帮了{m1}，{m0}不服气地换地方数。',stars:1,souvenir:''},
      '都不帮':{result:'你说别数了，星星是看不完的，三个人就都安静地仰着头。',companionReply:'{m0}轻声说：「嗯，确实看不完。」',memory:'夜里的星星，三个人放弃了数，只是安静地看。',stars:2,souvenir:''}
    }}
];

// ==================== 6. 小游戏事件（真实可玩）====================
// game 字段由引擎分派；guess/coin 需 choiceText（选项文案数组）；match/find 需 items
var JOURNEY_MINIGAME=[
  {title:'猜猜哪只手',
    game:'guess',
    scene:'{name}忽然停住，把一只手背到身后，又伸出来，攥着拳头。',
    companionAction:'{name}把两个拳头伸到你面前。',
    companionLine:'「猜猜看，哪只手里有东西？」',
    choiceText:['左手','右手'],
    actions:{'左手':'你指了指{name}的左手','右手':'你指了指{name}的右手'},
    winReply:'{name}摊开手：「答对了，给你的奖励。」',
    loseReply:'{name}摊开空着的那只手：「猜错了，下次可要看清一点。」',
    winMemory:'你猜中了{name}藏在手里的东西，TA说给你奖励。',
    loseMemory:'你猜错了{name}藏东西的手，TA得意地晃了晃。',
    winStars:2,loseStars:1,winSouvenir:'🌟 猜中的小奖励'},
  {title:'抛硬币',
    game:'coin',
    scene:'你们在小摊前决定买不买一样东西，谁也拿不定主意。',
    companionAction:'{name}从口袋里摸出一枚硬币，拇指一弹。',
    companionLine:'「正面就买，反面就不买，公平吧？」',
    choiceText:['正面','反面'],
    actions:{'正面':'你压了正面','反面':'你压了反面'},
    winReply:'硬币在空中转了几圈，落下来：正面。{name}说：「那就买！」',
    loseReply:'硬币落下来：反面。{name}摊手：「天意如此，走吧。」',
    winMemory:'抛硬币定购物的去留，你压中了正面。',
    loseMemory:'抛硬币决定买不买，硬币落了个反面，你们空手而归。',
    winStars:1,loseStars:1},
  {title:'翻牌配对',
    game:'match',
    scene:'小摊上摆着六张背面朝上的卡片，摊主说翻到一对就送小礼物。',
    companionAction:'{name}搓了搓手，指着卡片。',
    companionLine:'「一人翻一次，看我们能不能配上一对。」',
    choiceText:['翻两张看看','看{name}翻'],
    actions:{'翻两张看看':'你连翻了两张，记住了图案的位置','看{name}翻':'你让{name}先翻了两张'},
    winReply:'第二次，你准确地翻出配对的图案，摊主笑着递来小礼物。',
    loseReply:'你翻开了两张不同的图案，{name}笑着说：「没事，再来一次。」',
    winMemory:'翻牌配对的小摊上，你和{name}配出了一对，赢了个小礼物。',
    loseMemory:'翻牌配对没配成，{name}说再来一次。',
    winStars:2,loseStars:1,winSouvenir:'🃏 配对的小礼物'},
  {title:'找找看',
    game:'find',
    scene:'街边的橱窗里摆满小东西，{name}指着橱窗。',
    companionAction:'{name}说橱窗里藏着一个小惊喜，让你找。',
    companionLine:'「三秒内找到那个蓝色的贝壳，就请你吃糖。」',
    choiceText:['找到了','没找到'],
    actions:{'找到了':'你一眼就找到了藏在角落的蓝色贝壳','没找到':'你看了半天也没找到那个蓝色贝壳'},
    winReply:'{name}顺着你的目光看过去，笑了：「眼神不错，走，吃糖去。」',
    loseReply:'{name}指了指角落：「在那儿呢，再练练眼神。」',
    winMemory:'橱窗找物的挑战，你一眼就找到了蓝色贝壳。',
    loseMemory:'橱窗找物你没找到，{name}指给你看，说再练练眼神。',
    winStars:1,loseStars:1,winSouvenir:'🍬 赢来的糖'},
  {title:'拍一张照片',
    game:'photo',
    scene:'夕阳正好，你们站在一片开阔的地方，光把一切都镀成金色。',
    companionAction:'{name}把手机递给你。',
    companionLine:'「选一个拍法，今天的夕阳只有这一场。」',
    choiceText:['拍风景','拍{name}','一起合照'],
    actions:{'拍风景':'你举起手机，拍下整片金色的夕阳','拍{name}':'你把镜头对准{name}，TA愣了一下又笑了','一起合照':'你举起手机，把夕阳和你们一起收进画面'},
    winReply:'照片拍好了，{name}凑过来看，满意地点了点头。',
    loseReply:'照片拍好了，{name}凑过来看，满意地点了点头。',
    winMemory:'金色的夕阳下，你们留下了一张喜欢的照片。',
    loseMemory:'',
    winStars:2,loseStars:0,photo:true},
  {title:'猜价格',
    game:'price',
    scene:'路边摊上摆着一排手工陶瓷，其中一个杯子你看了很久。',
    companionAction:'{name}小声说。',
    companionLine:'「猜猜这个杯子多少钱？猜对了算我请。」',
    choiceText:['20 元','35 元','50 元'],
    actions:{'20 元':'你猜这个杯子 20 元','35 元':'你猜这个杯子 35 元','50 元':'你猜这个杯子 50 元'},
    winReply:'摊主说出的价格正好被你猜中，{name}愿赌服输，买了单。',
    loseReply:'摊主报出的价格和你猜的不一样，{name}还是把它买了下来。',
    winMemory:'猜价格猜了个正着，{name}请客买下了那个杯子。',
    loseMemory:'猜价格差了一点，{name}还是把杯子买了下来。',
    winStars:2,loseStars:1,winSouvenir:'🏺 猜中的陶瓷杯'},
  {title:'石头剪刀布',
    game:'rps',
    scene:'你们在一家店门口纠结要不要进去，谁也说不动谁。',
    companionAction:'{name}伸出手。',
    companionLine:'「老规矩，石头剪刀布，赢的人说了算。」',
    choiceText:['石头','剪刀','布'],
    actions:{'石头':'你出了石头','剪刀':'你出了剪刀','布':'你出了布'},
    winReply:'{name}出了个正好被克的手势，愿赌服输：「行，听你的。」',
    loseReply:'{name}的手势正好克了你：「看吧，天意如此，听我的。」',
    winMemory:'石头剪刀布赢下了{name}，TA说听你的。',
    loseMemory:'石头剪刀布输给了{name}，TA得意地说听TA的。',
    winStars:1,loseStars:1},
  {title:'数星星',
    game:'star',
    condition:'夜晚',
    scene:'夜里你们坐在台阶上，满天星星亮得刚刚好。',
    companionAction:'{name}仰着头，认真地指着一片天。',
    companionLine:'「数到十颗，就许一个愿，敢不敢？」',
    choiceText:['数到十','数到二十','先许愿'],
    actions:{'数到十':'你仰着头，认真数了十颗星','数到二十':'你数了二十颗，数到眼花','先许愿':'你没数，闭上眼睛先许了愿'},
    winReply:'你数得又快又准，{name}说：「好了，愿望可以许得大一点。」',
    loseReply:'你数到一半数乱了，{name}笑着：「那就随便许一个吧。」',
    winMemory:'数星星的夜里，你数够了十颗，许了一个愿望。',
    loseMemory:'数星星数到一半乱了，{name}说随便许一个也行。',
    winStars:1,loseStars:1}
];

// ==================== 7. 稀有隐藏事件（低概率，金色）====================
var JOURNEY_HIDDEN=[
  {title:'一场流星雨',
    condition:'夜晚',
    scene:'夜空忽然同时划过好几道流星，像有人在天上撒了一把亮晶晶的糖。',
    companionAction:'{name}猛地拽住你的袖子，声音都在发抖。',
    companionLine:'「快看！是流星雨！快许愿！」',
    interactions:[{name:'一起许愿',playerAction:'你闭上眼，和{name}一起许了愿'},{name:'看呆',playerAction:'你看着满天的流星，一时忘了动作'}],
    outcomes:{
      '一起许愿':{result:'你们同时闭上眼，又同时睁开，谁也没说许了什么。',companionReply:'{name}小声说：「我的愿望里，有你。」',memory:'一场流星雨，和{name}同时许了愿，TA说愿望里有你。',stars:3,souvenir:'🌠 流星雨的纪念'},
      '看呆':{result:'流星一颗接一颗地划过，你站在原地，仰着头看完了整场。',companionReply:'{name}在旁边轻声说：「这样的夜晚，一辈子可能就一次。」',memory:'你看完了一整场流星雨，{name}说一辈子可能就一次。',stars:3,souvenir:'🌠 一整场流星雨'}
    }},
  {title:'白色的狐狸',
    scene:'林间的空地上，一只白狐狸站在落叶里，正看着你们。',
    companionAction:'{name}屏住呼吸，轻轻拉住你，让你别动。',
    companionLine:'「别动……它好像不怕我们。」',
    interactions:[{name:'安静站着',playerAction:'你们站着不动，白狐狸看了一会儿，转身走进林子'},{name:'慢慢走近',playerAction:'你放轻脚步往前走了两步，白狐狸歪了歪头'}],
    outcomes:{
      '安静站着':{result:'白狐狸在落叶里站了一会儿，然后不紧不慢地走进林子深处。',companionReply:'{name}松了口气：「像做了个梦。」',memory:'林间空地上见到一只白狐狸，安静地看着你们离开。',stars:3,souvenir:'🦊 白狐的幸运'},
      '慢慢走近':{result:'你走近两步，白狐狸没有跑，反而歪了歪头，像在打量你。',companionReply:'{name}小声说：「它好像在记住我们。」',memory:'你走近了一只白狐狸，它歪着头，像在记住你们。',stars:3,souvenir:''}
    }},
  {title:'月光下的门',
    condition:'夜晚',
    scene:'一条不起眼的小巷深处，月光正好落在一扇木门上，门没锁。',
    companionAction:'{name}停在门前，回头看你。',
    companionLine:'「这扇门……好像专门等着今晚有人推开。」',
    interactions:[{name:'推开看看',playerAction:'你轻轻推开那扇门，走了进去'},{name:'记下位置',playerAction:'你记住这扇门的位置，决定改天白天再来'}],
    outcomes:{
      '推开看看':{result:'门后是一个小小的庭院，月光把石桌石凳照得发白，像另一个世界。',companionReply:'{name}轻声说：「原来门后面，藏着一个安静的月亮。」',memory:'月光下的门后，藏着一个安静的、被月亮照亮的小庭院。',stars:3,souvenir:'🌙 月光庭院'},
      '记下位置':{result:'你们记住了那扇门的位置，回头看了看月光，决定明天再来。',companionReply:'{name}说：「那明天，我们就是知道秘密的人了。」',memory:'一扇月光下的门，你们记住了位置，打算白天再来。',stars:2,souvenir:''}
    }},
  {title:'神秘礼物盒',
    scene:'路边一只系着丝带的旧木盒，放在台阶上，像是专门留给谁。',
    companionAction:'{name}蹲下来，小心地碰了碰丝带。',
    companionLine:'「盒子上没有名字……像是给路过的人的。」',
    interactions:[{name:'打开',playerAction:'你轻轻解开丝带，打开木盒'},{name:'放回去',playerAction:'你想了想，把木盒放回原位，没动'}],
    outcomes:{
      '打开':{result:'盒子里躺着一颗包着玻璃纸的糖，和一张写着「给今天开心的人」的字条。',companionReply:'{name}把糖剥开递给你：「它说得对，今天要开心。」',memory:'路边一只神秘木盒，里面有一颗糖和一张写着「给今天开心的人」的字条。',stars:3,souvenir:'🍬 神秘盒子里的糖'},
      '放回去':{result:'你们把木盒放回原位，让那份惊喜继续等着下一个人。',companionReply:'{name}说：「我们把好运留给了别人，也挺好。」',memory:'路边一只神秘木盒，你们没打开，把好运留给了下一个人。',stars:2,souvenir:''}
    }},
  {title:'神秘小屋',
    scene:'森林边缘立着一座小木屋，烟囱正冒着细烟，门口亮着一盏灯。',
    companionAction:'{name}站在门外，犹豫着要不要敲门。',
    companionLine:'「这种小屋，只在故事里见过。」',
    interactions:[{name:'敲门',playerAction:'你敲了敲门，屋里传来脚步声'},{name:'绕一圈看看',playerAction:'你们绕着小屋转了一圈，看了看窗台的花'}],
    outcomes:{
      '敲门':{result:'开门的是一位老奶奶，她笑着请你们喝了杯热茶，聊了一会儿才放你们走。',companionReply:'{name}走出门还回头挥手：「像故事里的情节。」',memory:'森林边的小屋，一位老奶奶请你们喝了杯热茶。',stars:3,souvenir:'🍵 小屋的热茶'},
      '绕一圈看看':{result:'小屋窗台上摆着几盆花，窗边挂着一串风铃，安静又温柔。',companionReply:'{name}说：「不打扰它了，让小屋继续做它自己的梦。」',memory:'森林边的小屋，你们绕着看了看窗台的花和风铃，没打扰它。',stars:2,souvenir:''}
    }},
  {title:'神秘信件',
    scene:'风把一封信吹到你们脚边，信封是淡蓝色的，封口还涂着蜡。',
    companionAction:'{name}捡起来，翻来覆去看了看。',
    companionLine:'「没有收件人……只有一句『给捡到它的人』。」',
    interactions:[{name:'拆开',playerAction:'你轻轻拆开封口，展开里面的信纸'},{name:'放回风里',playerAction:'你犹豫了一下，把信放回风里'}],
    outcomes:{
      '拆开':{result:'信纸上只写着一句话：「不管你是谁，祝你今天走过一条好看的路。」',companionReply:'{name}念完，安静了一下：「那我们就走过了一条。」',memory:'一封神秘的蓝色信，写着祝你今天走过一条好看的路。',stars:3,souvenir:'💌 神秘的信'},
      '放回风里':{result:'信被风卷起来，在空中翻了个身，向着远处飞去。',companionReply:'{name}看着它飞远：「它一定还有下一站。」',memory:'一封没有收件人的信，你们放回了风里，让它继续旅行。',stars:2,souvenir:''}
    }},
  {title:'极光的夜晚',
    condition:'夜晚',
    scene:'夜空忽然泛开一层绿色的光，像有人在天上泼了一桶极光。',
    companionAction:'{name}仰着头，好半天说不出话。',
    companionLine:'「这里……居然能看到极光。」',
    interactions:[{name:'一起看',playerAction:'你们并肩站着，看完了一场完整的极光'},{name:'拍照',playerAction:'你举起手机，但怎么拍都拍不出眼睛看到的样子'}],
    outcomes:{
      '一起看':{result:'极光在头顶缓缓流动，像一条会呼吸的河。',companionReply:'{name}轻声说：「相机拍不下来，就记在眼睛里。」',memory:'一场绿色的极光，和{name}看完了一整场，记在眼睛里。',stars:3,souvenir:'🌌 极光之夜'},
      '拍照':{result:'照片里的极光淡淡的，没有亲眼看到的百分之一好看。',companionReply:'{name}说：「没事，眼睛看到的那份，我们都有。」',memory:'极光的夜晚，照片拍不出它的好看，但眼睛记住了。',stars:3,souvenir:''}
    }},
  {title:'萤火虫山谷',
    condition:'夜晚',
    scene:'一条小路通向山谷，越往里走，周围的绿光越多，像落了一山谷的星星。',
    companionAction:'{name}站在原地，被围过来的萤火虫照亮了脸。',
    companionLine:'「它们……好像把我们当成了一盏灯。」',
    interactions:[{name:'站着不动',playerAction:'你们站着，让萤火虫在身边绕了一圈又一圈'},{name:'伸手接一只',playerAction:'你伸出手，一只萤火虫停在你的指尖'}],
    outcomes:{
      '站着不动':{result:'萤火虫的光一会儿亮一会儿暗，像整座山谷在呼吸。',companionReply:'{name}说：「我想把这一刻，存在最里面的口袋里。」',memory:'萤火虫山谷里，你们站着，被一整座山谷的绿光包围。',stars:3,souvenir:'✨ 萤火虫的光'},
      '伸手接一只':{result:'萤火虫停在你的指尖，光一亮一暗，像在跟你说话。',companionReply:'{name}轻声说：「它选了你的手。」',memory:'一只萤火虫停在你指尖，{name}说它选了你。',stars:3,souvenir:''}
    }},
  {title:'会说话的老猫',
    scene:'巷子深处一只老猫蹲在墙头，看见你们，居然开口说了句话。',
    companionAction:'{name}猛地停住，回头看你，眼睛里全是难以置信。',
    companionLine:'「它……它刚才是不是说话了？」',
    interactions:[{name:'回它一句',playerAction:'你学着猫的腔调，回了一句'},{name:'问{name}听到没',playerAction:'你问{name}，刚才是不是也听到了'}],
    outcomes:{
      '回它一句':{result:'老猫眯起眼看了你们一会儿，跳下墙头，钻进了巷子深处。',companionReply:'{name}半天才回过神：「刚才那件事，就我们两个知道。」',memory:'巷子深处的老猫开口说了句话，只有你们两个人知道。',stars:3,souvenir:'🐈 老猫的秘密'},
      '问{name}听到没':{result:'{name}点了点头，两个人对视一眼，谁也没再提这件事。',companionReply:'{name}小声说：「走吧，当没听见。」',memory:'一只会说话的老猫，你们决定把这件事当成两个人的秘密。',stars:3,souvenir:''}
    }},
  {title:'许愿井',
    scene:'古树下面有一口石井，井沿刻着「投一枚，圆一愿」。',
    companionAction:'{name}在口袋里摸了半天，摸出一枚硬币。',
    companionLine:'「不知道传说灵不灵，但想试试。」',
    interactions:[{name:'投硬币',playerAction:'你把硬币投进井里，听它落水的回声'},{name:'只围着看',playerAction:'你们围着井沿看了看，没投硬币'}],
    outcomes:{
      '投硬币':{result:'硬币落水的声音很轻，在井里荡了一下，像应了一声。',companionReply:'{name}说：「我许的愿，跟你有关系。」',memory:'许愿井边，{name}投了一枚硬币，说愿望跟你有关。',stars:3,souvenir:'🪙 许愿井的回声'},
      '只围着看':{result:'井沿上刻满了名字和愿望，有的字迹已经很模糊了。',companionReply:'{name}说：「他们许的愿，好像都还留在这里。」',memory:'许愿井边，你们看了满满一井沿的愿望，没投硬币。',stars:2,souvenir:''}
    }},
  {title:'神秘的卖花人',
    scene:'街角不知何时多了一个卖花的小摊，摊主戴着斗笠，看不清脸。',
    companionAction:'{name}走过去，挑了挑，最后拿起一束白色的花。',
    companionLine:'「这个花……好像在哪里见过。」',
    interactions:[{name:'买下来',playerAction:'你买下那束白花，摊主笑了笑，什么也没说'},{name:'问花的名字',playerAction:'你问摊主这花叫什么名字，TA只说了两个字'}],
    outcomes:{
      '买下来':{result:'摊主把花递给你，在你掌心放了一枚很小的种子，然后收摊走了。',companionReply:'{name}看着摊主消失的方向：「这个摊子，好像只为我们摆的。」',memory:'神秘的卖花人卖给你一束白花，还留了一枚种子。',stars:3,souvenir:'🤍 神秘的白花'},
      '问花的名字':{result:'摊主说了两个字：「缘分。」然后笑了笑，不再说话。',companionReply:'{name}重复了一遍：「缘分……记住了。」',memory:'神秘卖花人说的两个字，你们记住了：缘分。',stars:3,souvenir:''}
    }},
  {title:'只有一盏灯的小巷',
    condition:'夜晚',
    scene:'深夜的巷子里只有一盏路灯亮着，其余都熄了，像专门为你们留着。',
    companionAction:'{name}在灯下停下来，仰头看了看那盏灯。',
    companionLine:'「你说，这一盏灯，是不是在等我们路过？」',
    interactions:[{name:'在灯下站一会儿',playerAction:'你们在灯下站了一会儿，影子被拉得很长'},{name:'继续走',playerAction:'你看了那盏灯一眼，拉着{name}继续往前走'}],
    outcomes:{
      '在灯下站一会儿':{result:'灯下很安静，只有你们的影子，和远处传来的虫鸣。',companionReply:'{name}说：「这个夜晚，好像专门留给了我们。」',memory:'深夜只有一盏灯的小巷，你们在灯下站了一会儿。',stars:3,souvenir:'🏮 一盏灯'},
      '继续走':{result:'你们走出小巷时回头，那盏灯还亮着，像在目送。',companionReply:'{name}说：「它好像，把我们送到了这里。」',memory:'走过只有一盏灯的小巷，那盏灯像在目送你们。',stars:2,souvenir:''}
    }}
];

// ==================== 8. 梦角主动事件扩充（+10）====================
JOURNEY_COMPANION_EVENTS=JOURNEY_COMPANION_EVENTS.concat([
  {title:'发现隐藏小摊',
    scene:'{name}走着走着，忽然拉住你的袖子。',
    companionAction:'{name}指向一条不起眼的小巷，巷口飘着香。',
    companionLine:'「等等——那边有个小摊，我闻到香味了，去看看？」',
    interactions:[{name:'跟TA去',playerAction:'你跟{name}拐进小巷，找到了那个小摊'},{name:'记下位置',playerAction:'你们记下小巷的位置，说改天来'}],
    outcomes:{
      '跟TA去':{result:'巷子里的小摊卖的是现做的糖画，摊主正给一条龙点睛。',companionReply:'{name}眼睛亮亮的：「我就说这边有惊喜吧。」',memory:'{name}凭香味发现了一个藏在巷子里的小摊。',stars:2,souvenir:'🍭 糖画'},
      '记下位置':{result:'你们在巷口看了看，把位置记了下来，约好明天来。',companionReply:'{name}说：「有期待，明天就有奔头。」',memory:'{name}发现了巷子里的小摊，你们约好明天来。',stars:1,souvenir:''}
    }},
  {title:'TA走到前面去了',
    scene:'走着走着，{name}不知道什么时候走到了前面。',
    companionAction:'{name}回头，发现你还落在后面，站住了。',
    companionLine:'「你们怎么这么慢？前面好像有好玩的东西。」',
    interactions:[{name:'追上去',playerAction:'你小跑几步追上去'},{name:'让TA等等',playerAction:'你说等等，慢慢走才有意思'}],
    outcomes:{
      '追上去':{result:'前面确实有个小喷泉，水花在太阳里亮晶晶的。',companionReply:'{name}指着喷泉：「你看，我说有东西吧。」',memory:'{name}走到前面发现了小喷泉，回头叫你。',stars:1,souvenir:''},
      '让TA等等':{result:'{name}虽然嘴上催，还是放慢脚步等你。',companionReply:'「行吧，反正今天的路都是我们的。」',memory:'{name}催你快走，最后还是放慢脚步等了你。',stars:1,souvenir:''}
    }},
  {title:'TA想学一件事',
    scene:'路边有人在打太极，动作慢悠悠的，很有味道。',
    companionAction:'{name}停下脚步，认真看了一会儿。',
    companionLine:'「我想学这个……你陪我看完，等我学会打给你看。」',
    interactions:[{name:'陪着看',playerAction:'你站在{name}旁边，陪TA把一段太极看完'},{name:'教TA',playerAction:'你装作会的样子，比划了两下，逗得{name}笑'}],
    outcomes:{
      '陪着看':{result:'打太极的人收势离开，{name}还在原地比划，学得有模有样。',companionReply:'{name}说：「记住动作了，回去练给你看。」',memory:'{name}说要学太极，你陪着TA看完了一段。',stars:1,souvenir:''},
      '教TA':{result:'你比划得歪歪扭扭，{name}学得更歪，两个人笑成一团。',companionReply:'「算了算了，我们还是别学了。」',memory:'你教{name}打太极，比划得两个人笑成一团。',stars:1,souvenir:''}
    }},
  {title:'TA捡到奇怪的东西',
    scene:'{name}忽然蹲下去，捡起路边一样亮晶晶的东西。',
    companionAction:'{name}摊开手心，是一枚磨得发亮的玻璃珠。',
    companionLine:'「你看，这个珠子……像一颗小星球。」',
    interactions:[{name:'一起看',playerAction:'你凑过去，看那枚玻璃珠里的纹路'},{name:'帮TA收好',playerAction:'你说收好，就当今天的幸运珠'}],
    outcomes:{
      '一起看':{result:'玻璃珠里有一条深蓝色的纹路，像一小片宇宙。',companionReply:'{name}说：「说不定是哪颗星球掉下来的。」',memory:'{name}捡到一枚像小星球的玻璃珠，你们看了很久。',stars:2,souvenir:'🔮 小星球玻璃珠'},
      '帮TA收好':{result:'{name}把玻璃珠放进口袋，拍了拍：「当幸运珠用。」',companionReply:'「那它现在要管两个人的好运了。」',memory:'{name}把捡到的玻璃珠收好，说当两个人的幸运珠。',stars:1,souvenir:''}
    }},
  {title:'TA想拍一张照',
    scene:'傍晚的光线正好，{name}忽然停下来，举起手机。',
    companionAction:'{name}对着天空拍了一张，又对着路拍了张，然后转向你。',
    companionLine:'「别动，这个光线拍你正好。」',
    interactions:[{name:'摆个姿势',playerAction:'你站好，配合地摆了个姿势'},{name:'挡住镜头',playerAction:'你笑着用手挡住镜头说不拍'}],
    outcomes:{
      '摆个姿势':{result:'快门响了一下，{name}看着照片，点了点头。',companionReply:'「这张拍得好，我要留着。」',memory:'{name}主动拍了一张照片，说这张要留着。',stars:1,souvenir:'📸 TA拍的照片'},
      '挡住镜头':{result:'你挡住了镜头，{name}放下手机，说那就记在脑子里。',companionReply:'「行吧，那你负责记住这个下午。」',memory:'你挡住了{name}的镜头，TA说那就让你记住下午。',stars:1,souvenir:''}
    }},
  {title:'TA发现一条近路',
    scene:'{name}在一堵矮墙前停下来，探头往里看了看。',
    companionAction:'{name}回头，指了指墙边一条长满草的小径。',
    companionLine:'「这条路我昨天走过，能少绕一大圈，走不走？」',
    interactions:[{name:'跟TA走',playerAction:'你跟{name}穿过那条小径'},{name:'走大路',playerAction:'你说还是走大路稳一点'}],
    outcomes:{
      '跟TA走':{result:'小径尽头是一小片菜地，一位大爷正浇菜，看见你们笑了笑。',companionReply:'{name}说：「看，走小路还能遇见熟人。」',memory:'{name}带你走了一条近路，尽头是一片菜地。',stars:1,souvenir:''},
      '走大路':{result:'你们绕了大路，{name}一路上念叨着那条近路能省多少步。',companionReply:'「你看，我说的没错吧，大路多走十分钟。」',memory:'你没走{name}发现的近路，TA念叨了一路。',stars:1,souvenir:''}
    }},
  {title:'TA想把风景画下来',
    scene:'眼前的风景像一幅画，{name}站在那里看了很久。',
    companionAction:'{name}掏出随身带的小本子，对着风景画了几笔。',
    companionLine:'「我想把它画下来……送给你。」',
    interactions:[{name:'看着TA画',playerAction:'你安静地站在旁边，看{name}画完'},{name:'帮TA看构图',playerAction:'你帮{name}看了看构图，提了个建议'}],
    outcomes:{
      '看着TA画':{result:'{name}画得认真，风把画纸吹起一角，TA赶紧压住。',companionReply:'画完{name}撕下那页递给你：「送你了，别嫌弃。」',memory:'{name}把眼前的风景画下来送给了你。',stars:2,souvenir:'🖼️ TA画的风景'},
      '帮TA看构图':{result:'你建议把天空留多一点，{name}想了想，改了改，确实更好看了。',companionReply:'{name}说：「你的眼光不错，这幅算我们合作的。」',memory:'你帮{name}调整了构图，那幅画算两个人合作的。',stars:2,souvenir:''}
    }},
  {title:'TA想交换一个秘密',
    scene:'天色暗下来，{name}走着走着，忽然放慢脚步。',
    companionAction:'{name}偏过头，声音放得很轻。',
    companionLine:'「我们交换一个秘密吧，你先说，还是我先说？」',
    interactions:[{name:'先说',playerAction:'你先说了一个自己的小秘密'},{name:'让TA先说',playerAction:'你说让{name}先来'}],
    outcomes:{
      '先说':{result:'你说完，{name}安静了一会儿，也还了你一个。',companionReply:'「扯平了，现在我们都握着对方的秘密了。」',memory:'夜色里，你们交换了一个秘密，谁也没再提起。',stars:3,souvenir:''},
      '让TA先说':{result:'{name}讲了一个很小很小的事，讲完自己先松了口气。',companionReply:'「说出来轻松多了……轮到你了。」',memory:'{name}先讲了一个秘密，你们在夜色里交换了它。',stars:2,souvenir:''}
    }},
  {title:'TA停下来看云',
    scene:'风忽然停了，云在天上停成一大朵，像睡着了。',
    companionAction:'{name}抬头看了很久，忽然叫你。',
    companionLine:'「你看这朵云，像不像一只趴着的猫？」',
    interactions:[{name:'一起看',playerAction:'你抬头，和{name}一起看那朵云'},{name:'比划形状',playerAction:'你伸出手，比了比云的形状'}],
    outcomes:{
      '一起看':{result:'那朵云慢慢散开，又聚起来，变成了一只别的动物。',companionReply:'{name}说：「它还会变的，我们多看一会儿。」',memory:'{name}叫住你，一起看了一朵会变形状的云。',stars:1,souvenir:''},
      '比划形状':{result:'你比出的形状和云不太像，{name}笑得直摇头。',companionReply:'「你那个是猫，这个是狗，差远啦。」',memory:'你比划云的形状比错了，{name}笑你是猫狗不分。',stars:1,souvenir:''}
    }},
  {title:'TA想找一家老店',
    scene:'{name}忽然在一张旧地图前停下来，看了又看。',
    companionAction:'{name}指着地图上一个标着星号的地方。',
    companionLine:'「等等，听说这里有家开了几十年的老店，我找它好久了。」',
    interactions:[{name:'陪TA找',playerAction:'你陪{name}按着地图，一条街一条街地找'},{name:'问路人',playerAction:'你拦住一位路人，问那家老店的位置'}],
    outcomes:{
      '陪TA找':{result:'老店在一条背街的巷子里，门脸很小，招牌已经褪色。',companionReply:'{name}站在门口，有点激动：「找到了。」',memory:'你陪{name}找到了TA找了很久的那家老店。',stars:2,souvenir:''},
      '问路人':{result:'路人指了路，你们顺利找到，{name}说还是你效率高。',companionReply:'「谢谢你，不然我可能还要再绕半天。」',memory:'你帮{name}问到路，找到了那家老店。',stars:1,souvenir:''}
    }}
]);

// ==================== 9. 连锁剧情扩充（+4 组）====================
JOURNEY_STORIES.oldpostcard={
  key:'oldpostcard',name:'旧明信片',
  stages:[
    {title:'书店里的旧明信片',
      scene:'书店的旧书堆里，夹着一张泛黄的明信片，边角已经卷起。',
      companionAction:'{name}抽出来看了看正面，是一幅很旧的水彩风景画。',
      companionLine:'「你看，这张明信片……像很久以前的人寄的。」',
      interactions:[{name:'看正面',playerAction:'你接过明信片，看那幅褪色的水彩画'},{name:'看看寄件人',playerAction:'你翻到背面，想看看寄件人是谁'}],
      outcomes:{
        '看正面':{result:'水彩画上是一片山脚下的村庄，落款是一行小字，已经看不太清。',companionReply:'{name}说：「这个风景，不知道现在还找不找得到。」',memory:'旧书堆里夹着一张褪色的水彩明信片。',stars:2,souvenir:'📮 旧明信片'},
        '看看寄件人':{result:'背面的字迹很淡，只隐约能认出收件人的地名，寄件人看不清了。',companionReply:'{name}说：「那我们也算替它走了一程。」',memory:'旧明信片的背面字迹很淡，你们没看清寄件人。',stars:1,souvenir:''}
      }},
    {title:'背面的字',
      scene:'第二天路过同一家书店，你们又想起了那张明信片。',
      companionAction:'{name}把明信片翻过来，在光下仔细看了看。',
      companionLine:'「等等——背面好像还有一行字，很淡，要对着光才看得到。」',
      interactions:[{name:'对着光看',playerAction:'你们把明信片对着光，辨认那行淡字'},{name:'用铅笔拓',playerAction:'你找来一支铅笔，轻轻在纸上拓那行字'}],
      outcomes:{
        '对着光看':{result:'光下，那行字慢慢显出来：『寄自山脚下的旧旅馆，等一个人来。』',companionReply:'{name}念完，安静了一下：「山脚下的旧旅馆……」',memory:'旧明信片背面还有一行淡字，写着山脚下的旧旅馆。',stars:2,souvenir:''},
        '用铅笔拓':{result:'铅笔轻轻扫过，字迹浮现在纸上，比想象中清楚。',companionReply:'{name}说：「这下，它想说的话我们全知道了。」',memory:'你们用铅笔拓出了旧明信片上那行几乎看不见的字。',stars:2,souvenir:''}
      }},
    {title:'打听旧旅馆',
      scene:'你们拿着明信片，沿路打听那座「山脚下的旧旅馆」。',
      companionAction:'{name}拦住一位当地老人，把明信片递过去。',
      companionLine:'「爷爷说，山脚下确实有一家旧旅馆，很多年没营业了。」',
      interactions:[{name:'一起去看看',playerAction:'你们一起走向山脚下的旧旅馆'},{name:'先歇脚',playerAction:'你们在路边的石凳上坐下来，看了看明信片'}],
      outcomes:{
        '一起去看看':{result:'旧旅馆的招牌还挂着，门锁着，但院子里种着和画上一样的花。',companionReply:'{name}站在门口：「和明信片上的风景，是同一个地方。」',memory:'你们找到了明信片上那家山脚下的旧旅馆。',stars:2,souvenir:''},
        '先歇脚':{result:'石凳上，你们对着明信片，想象当年住在这里的人。',companionReply:'{name}说：「他一定很想念这个地方。」',memory:'去找旧旅馆的路上，你们在石凳上看了很久那张明信片。',stars:1,souvenir:''}
      }},
    {title:'明信片上的地方',
      scene:'旧旅馆的院子一角，和明信片上的水彩画几乎一模一样。',
      companionAction:'{name}把明信片举起来，和眼前的风景叠在一起比了比。',
      companionLine:'「你看，就是这棵树的形状，还有这座山的轮廓。」',
      interactions:[{name:'同角度拍一张',playerAction:'你举起手机，在明信片同样的角度拍了一张'},{name:'把明信片留下',playerAction:'你想了想，把明信片放回院子里的信箱上'}],
      outcomes:{
        '同角度拍一张':{result:'你拍下的照片和明信片上的画，几乎可以重叠。',companionReply:'{name}看看照片又看看明信片：「它等到了这个角度。」',memory:'旧旅馆前，你们拍下了和明信片几乎一样的风景。',stars:3,souvenir:'📮 旧时光旅行回忆'},
        '把明信片留下':{result:'你们把明信片放回旧旅馆的信箱上，像让它回到原来的地方。',companionReply:'{name}轻声说：「它的旅程，在这里结束了。」',memory:'你们把旧明信片留在了它该在的地方，替它走完了旅程。',stars:3,souvenir:'📮 旧时光旅行回忆'}
      }}
  ]
};
JOURNEY_STORIES.oldtoy={
  key:'oldtoy',name:'走丢的小熊',
  stages:[
    {title:'路边的旧玩具',
      scene:'路边的长椅上，放着一只旧布熊，坐得端端正正，像在等人。',
      companionAction:'{name}蹲下来，看着那只小熊。',
      companionLine:'「它好像是被落在这里的……你看，它坐得这么乖。」',
      interactions:[{name:'拿起来看看',playerAction:'你拿起小熊，看到它胸前绣着一个名字'},{name:'原地等一等',playerAction:'你们在长椅边站了一会儿，看会不会有人来找'}],
      outcomes:{
        '拿起来看看':{result:'小熊胸前的布上绣着两个字，针脚歪歪的，像小孩子绣的。',companionReply:'{name}念出来：「『小年』……我们帮它找找吧。」',memory:'长椅上的旧布熊，胸前绣着「小年」两个字。',stars:2,souvenir:''},
        '原地等一等':{result:'等了一会儿，没有人来，风把小熊的耳朵吹得晃了晃。',companionReply:'{name}说：「没人来……那我们带它走吧。」',memory:'长椅上的布熊等了很久没人来，你们决定带上它。',stars:1,souvenir:''}
      }},
    {title:'帮小年找家',
      scene:'你们带着小熊走了一路，最后在公园门口的宣传栏前停下来。',
      companionAction:'{name}指着宣传栏上一张写满字的寻物启事。',
      companionLine:'「你看，有人找『小年』……是一只布熊。」',
      interactions:[{name:'打电话',playerAction:'你们按启事上的电话打过去，约好了见面地点'},{name:'按地址送',playerAction:'你们按启事上的地址，直接找了过去'}],
      outcomes:{
        '打电话':{result:'电话那头传来一个小孩的声音，听到「小年」两个字，一下子就哭了。',companionReply:'{name}握着电话：「别哭，我们把它送回去。」',memory:'你们按寻物启事，找到了丢小熊的小孩。',stars:2,souvenir:''},
        '按地址送':{result:'开门的阿姨听了来意，眼眶红了，说这是孩子最宝贝的玩具。',companionReply:'{name}把小熊递过去：「它坐得很乖，一直在等。」',memory:'你们把小熊送回了家，它坐得很乖，一直在等。',stars:2,souvenir:''}
      }},
    {title:'小熊回家了',
      scene:'小孩跑出来，一把抱住小熊，把小熊的脸埋进自己怀里。',
      companionAction:'{name}站在旁边，看着这一幕，笑了。',
      companionLine:'「你看，它终于等到了。」',
      interactions:[{name:'看着TA们',playerAction:'你们站在门口，看小孩抱着小熊不肯撒手'},{name:'挥手告别',playerAction:'你们朝小孩挥了挥手，转身离开'}],
      outcomes:{
        '看着TA们':{result:'小孩抱着小熊，朝你们鞠了一躬，小熊的手朝你们摆了摆。',companionReply:'{name}也朝小熊摆了摆手：「再见啦，小年。」',memory:'你们把小年送回了家，小孩抱着它，小熊朝你们摆了摆手。',stars:3,souvenir:'🧸 小年送你的纽扣'},
        '挥手告别':{result:'你们走出几步，身后传来小孩喊「谢谢」的声音，越来越远。',companionReply:'{name}说：「今天做了一件很好的事。」',memory:'你们把小年送回家，身后传来小孩的谢谢。',stars:3,souvenir:''}
      }}
  ]
};
JOURNEY_STORIES.lighthouse={
  key:'lighthouse',name:'深夜的灯塔',
  stages:[
    {title:'远处的光',
      condition:'夜晚',
      scene:'夜晚的海边，远处有一座灯塔，灯一下一下地转着光。',
      companionAction:'{name}望着灯塔的方向，看了很久。',
      companionLine:'「那盏灯，一晚要转多少圈呢？」',
      interactions:[{name:'走近看看',playerAction:'你们沿着海岸线，朝灯塔的方向走过去'},{name:'远远看着',playerAction:'你们站在远处，看灯塔的光一圈一圈地转'}],
      outcomes:{
        '走近看看':{result:'越走越近，灯塔的轮廓在夜色里越来越清楚。',companionReply:'{name}说：「走近了，好像它在等我们。」',memory:'深夜的海边，你们朝着灯塔的光走了过去。',stars:2,souvenir:''},
        '远远看着':{result:'灯塔的光一圈一圈，划破海面，又消失。',companionReply:'{name}说：「它一晚要转很多圈，但每一圈都是认真的。」',memory:'深夜的海边，你们远远看着灯塔的光一圈圈地转。',stars:2,souvenir:''}
      }},
    {title:'灯塔下的旧门',
      scene:'灯塔的入口有一扇旧铁门，虚掩着，门缝里透出昏黄的光。',
      companionAction:'{name}站在门口，犹豫了一下，轻轻推开门。',
      companionLine:'「好像没人锁……我们进去看看？」',
      interactions:[{name:'走进去',playerAction:'你们轻手轻脚地走进灯塔内部'},{name:'站在门口',playerAction:'你们没进去，只在门口探头看了看'}],
      outcomes:{
        '走进去':{result:'灯塔内部很旧，木梯吱呀作响，墙上贴着很多年前的守塔记录。',companionReply:'{name}小声说：「这里的时间，好像停住了。」',memory:'你们走进了深夜的灯塔，木梯吱呀作响。',stars:2,souvenir:''},
        '站在门口':{result:'昏黄的光从门缝里透出来，你们站在门口，没有打扰它。',companionReply:'{name}说：「不进去了，让它继续守夜吧。」',memory:'深夜的灯塔门口，你们没有进去，让它继续守夜。',stars:1,souvenir:''}
      }},
    {title:'守塔人的笔记',
      scene:'灯塔里的小桌上放着一本翻开的旧笔记，钢笔字工工整整。',
      companionAction:'{name}凑近看了一眼，念出上面的字。',
      companionLine:'「上面写着：『第 4021 夜，风浪很大，灯一直亮着。』」',
      interactions:[{name:'接着往后翻',playerAction:'你们翻到笔记的最后一页'},{name:'合上笔记',playerAction:'你看完，把笔记轻轻合上，放回原处'}],
      outcomes:{
        '接着往后翻':{result:'最后一页写着：「今晚有两个人走进灯塔，我听见了，祝他们一路顺风。」',companionReply:'{name}念完，两个人都安静了：「它知道我们来了。」',memory:'灯塔的守塔笔记，最后一页写着祝你们一路顺风。',stars:3,souvenir:'🕯️ 守塔人的祝福'},
        '合上笔记':{result:'你们把笔记合上放回原处，像替守塔人保守了一个秘密。',companionReply:'{name}轻声说：「四千多个夜晚，它都一个人记着。」',memory:'深夜的灯塔里，你们合上了一本记了四千多夜的笔记。',stars:2,souvenir:''}
      }}
  ]
};
JOURNEY_STORIES.paperboat={
  key:'paperboat',name:'纸船的信',
  stages:[
    {title:'河边的纸船',
      scene:'河边的石阶上，放着一只折好的纸船，船身湿了一点，像刚从水里捞起来。',
      companionAction:'{name}蹲下来，小心地拿起纸船。',
      companionLine:'「船里好像夹着什么东西。」',
      interactions:[{name:'展开纸船',playerAction:'你轻轻把纸船展开，看到纸上的字'},{name:'放回水里',playerAction:'你想了想，把纸船放回水面上，让它继续漂'}],
      outcomes:{
        '展开纸船':{result:'纸上写着几个字：「如果你看到，请在明早的桥头见我。」落款没有名字。',companionReply:'{name}念出来：「桥头……是前面那座桥吗？」',memory:'河边的纸船里夹着一张字条，约人明早在桥头见。',stars:2,souvenir:''},
        '放回水里':{result:'纸船在水面上晃了晃，顺着水流慢慢漂远了。',companionReply:'{name}看着它漂远：「它还有下一站。」',memory:'你们把纸船放回水里，让它继续漂。',stars:1,souvenir:''}
      }},
    {title:'明早的桥头',
      condition:'晴天',
      scene:'第二天一早，你们来到桥头，晨雾还没散尽。',
      companionAction:'{name}站在桥头，四处看了看，忽然指着桥下。',
      companionLine:'「你看，桥下有个老人在放纸船，一只接一只。」',
      interactions:[{name:'走过去',playerAction:'你们走下桥，来到老人身边'},{name:'远远看着',playerAction:'你们站在桥上，看老人放纸船'}],
      outcomes:{
        '走过去':{result:'老人抬起头，笑着说：「你们收到我的船啦？」原来那些字条都是TA放的。',companionReply:'{name}问为什么，老人说：「想看看有没有人愿意来。」',memory:'桥下的老人放了很多纸船，说想看看有没有人愿意来。',stars:3,souvenir:''},
        '远远看着':{result:'老人放完手里的纸船，朝桥上你们的方向看了一眼，笑了笑。',companionReply:'{name}说：「他好像知道我们收到了。」',memory:'你们远远看着老人放纸船，TA朝你们笑了笑。',stars:2,souvenir:''}
      }},
    {title:'老人的故事',
      scene:'老人坐在桥下的石头上，身边放着一小摞折好的纸船。',
      companionAction:'{name}坐下来，听老人说话。',
      companionLine:'「他说，年轻时跟人约定在这里见面，那个人没来，他就一直折纸船。」',
      interactions:[{name:'陪TA坐一会儿',playerAction:'你们在老人身边坐了一会儿'},{name:'也折一只船',playerAction:'你学着老人的样子，也折了一只纸船放下去'}],
      outcomes:{
        '陪TA坐一会儿':{result:'老人讲了很多以前的事，讲完说：「今天有人听，心里舒坦多了。」',companionReply:'{name}说：「那以后我们路过，都来听您讲。」',memory:'桥下，你们听一位老人讲了很久以前的故事。',stars:3,souvenir:'📄 一张折纸船的信纸'},
        '也折一只船':{result:'你折的船歪歪扭扭地漂出去，老人看着笑了：「这只船，有伴了。」',companionReply:'{name}说：「你看，它替我们陪着那些船了。」',memory:'你折了一只纸船放进河里，替你们陪着老人的船。',stars:3,souvenir:''}
      }}
  ]
};

// ==================== 10. 梦角间偶发小插曲（多人模式低概率）====================
// 与 JOURNEY_MULTI 不同：发生在两个梦角之间，玩家可旁观或介入
var JOURNEY_BANTER=[
  {title:'争论谁先到',
    scene:'两个梦角走在前面，越走越快，谁也不让谁。',
    companionAction:'两个人一边拌嘴一边往前走，还不忘回头看你的位置。',
    companionLine:'「那你也跟上来，一起评评理！」',
    members:[
      {action:'{m0}回头喊你。',line:'「你评评理，谁先到下一站算谁赢！」'},
      {action:'{m1}已经开始跑了。',line:'「赢的人说了算！」'}
    ],
    interactions:[{name:'旁观',playerAction:'你站在后面，看两个人比谁先到'},{name:'加入比赛',playerAction:'你也跑起来，说要一起比'},{name:'叫停',playerAction:'你喊了一声，让两个人别跑了，注意安全'}],
    outcomes:{
      '旁观':{result:'两个人跑到路口，几乎同时到，谁也不认输，最后决定并列第一。',companionReply:'{m0}喘着气：「那就算平手。」',memory:'两个梦角比谁先到，最后并列第一。',stars:1,souvenir:''},
      '加入比赛':{result:'你从后面超了过去，两个人愣住，然后笑着追上来。',companionReply:'{m1}喊：「你作弊，你没喊开始！」',memory:'你半路加入比赛，从两个人中间超了过去。',stars:1,souvenir:''},
      '叫停':{result:'你喊了一声，两个人慢下来，回头看你，有点不好意思。',companionReply:'{m0}说：「行行行，不跑了。」',memory:'你叫停了两个梦角的赛跑，说注意安全。',stars:1,souvenir:''}
    }},
  {title:'互相拍照',
    scene:'两个梦角互相举着手机，拍来拍去，谁也不服谁的拍照技术。',
    companionAction:'两个人互不相让地拍了几轮，最后一起看向你。',
    companionLine:'「你说，我们俩谁拍得好？」',
    members:[
      {action:'{m0}举着手机。',line:'「你这张拍糊了，看我的。」'},
      {action:'{m1}抢过手机。',line:'「那是因为你手抖！」'}
    ],
    interactions:[{name:'旁观',playerAction:'你站在旁边，看两个人互相吐槽对方的拍照技术'},{name:'当模特',playerAction:'你说那你们拍我吧，我给你们当模特'},{name:'当裁判',playerAction:'你拿过手机，说让我来拍'}],
    outcomes:{
      '旁观':{result:'两个人互拍了半天，最后挑了张都满意的，说合影留念。',companionReply:'{m1}说：「这张发群里，谁也不许删。」',memory:'两个梦角互相拍照吐槽，最后一起合了影。',stars:1,souvenir:''},
      '当模特':{result:'你站好，两个人一个喊「看这里」，一个喊「笑一个」，拍得比谁都认真。',companionReply:'{m0}看着照片：「还是你当模特效果好。」',memory:'你给两个梦角当模特，两个人拍得比谁都认真。',stars:1,souvenir:''},
      '当裁判':{result:'你接过手机，咔咔拍了两张，构图正好，两个人服气了。',companionReply:'{m1}说：「行，以后拍照都归你。」',memory:'你给两个梦角拍的照片，构图正好，都服气了。',stars:2,souvenir:''}
    }},
  {title:'偷偷分享零食',
    scene:'两个梦角以为你没注意，悄悄分着一包零食。',
    companionAction:'两个人压低声音，眼神还时不时往你这边飘。',
    companionLine:'「嘘——别出声，我们悄摸分完。」',
    members:[
      {action:'{m0}压低声音。',line:'「嘘，别让TA看见，就剩几颗了。」'},
      {action:'{m1}也压低声音。',line:'「那给我一颗，我就当没看见。」'}
    ],
    interactions:[{name:'假装没看见',playerAction:'你假装在看风景，让两个人以为你没发现'},{name:'伸手讨一颗',playerAction:'你忽然伸手：「我都听见了。」'}],
    outcomes:{
      '假装没看见':{result:'两个人分完了零食，{m1}还是悄悄留了一颗，趁你不注意塞给你。',companionReply:'{m0}说：「分你一颗，但刚才的事当没发生。」',memory:'两个梦角偷偷分零食，还是悄悄给你留了一颗。',stars:1,souvenir:''},
      '伸手讨一颗':{result:'你忽然开口，两个人吓了一跳，最后乖乖把零食都摊开让你挑。',companionReply:'{m1}说：「行吧，见者有份。」',memory:'你戳穿了两个梦角分零食，最后见者有份。',stars:1,souvenir:''}
    }},
  {title:'互相模仿',
    scene:'一个梦角学另一个说话，学得惟妙惟肖。',
    companionAction:'两个人你一句我一句地模仿，越学越起劲。',
    companionLine:'「你看TA，我说得像不像？」',
    members:[
      {action:'{m0}清了清嗓子，学{m1}说话。',line:'「『这个好好看，那个也好好看』——你一天要说八百遍。」'},
      {action:'{m1}被气笑。',line:'「哪有！我明明只说了一百遍！」'}
    ],
    interactions:[{name:'旁观',playerAction:'你站在旁边，看两个人斗嘴'},{name:'加入模仿',playerAction:'你也学起两个说话的样子'}],
    outcomes:{
      '旁观':{result:'两个人斗着嘴，越走越近，最后勾肩搭背地走，像没事发生过。',companionReply:'{m1}说：「算了，不跟你计较。」',memory:'两个梦角互相模仿斗嘴，最后又和好了。',stars:1,souvenir:''},
      '加入模仿':{result:'你学着两个人说话，学得比他们还像，两个人愣住，然后笑成一团。',companionReply:'{m0}说：「完了，被你说得我们俩都没法见人了。」',memory:'你加入模仿，学两个梦角说话，把他们逗笑了。',stars:1,souvenir:''}
    }},
  {title:'谁跟TA最熟',
    scene:'两个梦角忽然聊起你，聊着聊着声音大了起来。',
    companionAction:'两个人聊得正起劲，谁也没注意你已经走近了。',
    companionLine:'「反正，我说了算——啊，TA过来了。」',
    members:[
      {action:'{m0}挺起胸。',line:'「我跟TA比较熟，TA的口味我都知道。」'},
      {action:'{m1}不服气。',line:'「才不是，TA上次明明选了我推荐的那家。」'}
    ],
    interactions:[{name:'走过去',playerAction:'你走过去，问两个人在聊什么'},{name:'听下去',playerAction:'你放慢脚步，听两个人继续聊'}],
    outcomes:{
      '走过去':{result:'两个人看见你，一下子安静了，然后同时说：「没聊什么！」',companionReply:'{m0}小声嘀咕：「被本人听见了。」',memory:'两个梦角在背后聊你，被当场撞见，都说不聊了。',stars:1,souvenir:''},
      '听下去':{result:'你听见两个人把你知道的、不知道的事都数了一遍，越数越离谱。',companionReply:'{m1}最后说：「反正，跟你一起走，挺好的。」',memory:'你听见两个梦角在背后说了你一堆好话。',stars:2,souvenir:''}
    }},
  {title:'争着带路',
    scene:'到了路口，两个梦角一个说左一个说右，谁也不让。',
    companionAction:'两个人各指一个方向，谁都不肯先放下来。',
    companionLine:'「你听我的还是听TA的？」',
    members:[
      {action:'{m0}指着左边。',line:'「左边近，我昨天看过地图了。」'},
      {action:'{m1}指着右边。',line:'「右边好走，左边那个坡累死人了。」'}
    ],
    interactions:[{name:'让TA们石头剪刀布',playerAction:'你说别吵了，石头剪刀布定胜负'},{name:'自己带路',playerAction:'你说都别争了，我来带路'},{name:'看TA们吵',playerAction:'你站在一边，看两个人能争多久'}],
    outcomes:{
      '让TA们石头剪刀布':{result:'{m0}出了布，{m1}出了剪刀，{m1}得意地带路，{m0}愿赌服输。',companionReply:'{m0}说：「赢了归赢了，右边那个坡，你负责拉我。」',memory:'两个梦角争带路，石头剪刀布决出了胜负。',stars:1,souvenir:''},
      '自己带路':{result:'你说我带路，两个人互相看了一眼，都不说话了，乖乖跟上。',companionReply:'{m1}小声说：「也行，听你的。」',memory:'两个梦角争带路，你自己走到了前面，两个人乖乖跟上。',stars:1,souvenir:''},
      '看TA们吵':{result:'两个人吵着吵着，发现你已经走了，赶紧追上来：「等等我们！」',companionReply:'{m0}喊：「你也不说一声就带路！」',memory:'两个梦角争带路，你默默走了，两个人追了上来。',stars:1,souvenir:''}
    }}
];
